### ISSUE TITLE
Add filter by proposing MK to bill list, and add link to that filter from the MK page

### ISSUE THREAD

**Issue by ofri** [hasadna/Open-Knesset#142]
This type of page http://oknesset.org/bill/?member=826 exists, but the only way to get to it is from page like http://oknesset.org/member/by/bills_proposed/ (see also the other stage filters) Need to add it to the bill list filter, and then link from each MK page to the list, filtered to show bills proposed by that MK (possibly, add links to the list filtered by different bill stages - proposed, passed pre vote, etc.).

**Comment by daonb** [comment]
I'll try and re-design : the member page should contain a link to http://oknesset.org/bill/?member=XXX so the user can easily filter the MKs proposals. 
To do this we need to change the bill page so it remembers the current filter. Today, when I start with MKs proposals and try to filter them further I lose the MK filter.
Will be done as part of #345.
