### ISSUE TITLE
Votes against party/coalition are wrong

### ISSUE THREAD

**Issue by ofri** [hasadna/Open-Knesset#161]
for example, in http://oknesset.org/member/105/%D7%A2%D7%9E%D7%99%D7%A8-%D7%A4%D7%A8%D7%A5/ , click the question mark near משמעת קואליציה and you get a list of votes this MK voted against the coalition. its computed wrong - because in the previous knesset he was in a different party than other MKs in his current party, it is counted as if he voted against them, but they were not really his party/coalition _at the time of those votes_.

**Comment by alonisser** [comment]
@OriHoch  @morchickit  I believe this was a duplicate of  #555 (and the related issue) I think this can be safely closed

**Comment by OriHoch** [comment]
@morchickit @RacheliRoval please test to make sure it's fixed

**Comment by alonisser** [comment]
I believe I already fixed it a long time ago. ALSO the links are not there any more. Closing
