### ISSUE TITLE
Update mentions in press and media for the about page.

### ISSUE THREAD

**Issue by MeirKriheli** [hasadna/Open-Knesset#174]
Open Knesset's [About Page](http://oknesset.org/about/) contains a box of mentions in the media.

The content is not up to date, with the latest entry dated March, 2011. Please provide more links to be included in that box.

**Comment by daonb** [comment]
How about we change it to a link to: https://www.google.com/search?hl=iw&gl=il&tbm=nws&authuser=0&q=%22%D7%9B%D7%A0%D7%A1%D7%AA+%D7%A4%D7%AA%D7%95%D7%97%D7%94%22&oq=%22%D7%9B%D7%A0%D7%A1%D7%AA+%D7%A4%D7%AA%D7%95%D7%97%D7%94%22&gs_l=news-cc.3..43j43i53.4388.7636.0.7885.16.8.0.8.0.1.270.928.5j2j1.8.0...0.0...1ac.1.0qqB4cVmYmM
?

**Comment by morchickit** [comment]
Was done 3 months ago.
