### ISSUE TITLE
Improvements in item lists in tag page

### ISSUE THREAD

**Issue by ofri** [hasadna/Open-Knesset#177]
in pages like http://oknesset.org/tags/%D7%AA%D7%97%D7%91%D7%95%D7%A8%D7%94%20%D7%A6%D7%99%D7%91%D7%95%D7%A8%D7%99%D7%AA/ there is a list of related committee meetings. we need to:
1. add the name of the committee (above the topics)
2. add the number of participating mks (below the date)

in all lists (committee meetings, votes, bills) we need to present only 20 items by default, with a button to see more.

**Comment by daonb** [comment]
@nirfuzz how is it going?

**Comment by daonb** [comment]
Also need to fix a bug - the current kneseet active mks include past mks:
![active mks](https://cloud.githubusercontent.com/assets/36852/7860006/1cda6ff0-054e-11e5-9470-d653664eb3e7.png)
