### ISSUE TITLE
show annotations from protocols in MK page

### ISSUE THREAD

**Issue by orishahori** [hasadna/Open-Knesset#193]
Whenever a user annotates sentences in a protocol, the system will recognize the MK that said them, and will show them in the relevant MK page in a special box of annotations.
Example:
In this protocol - https://oknesset.org/committee/meeting/5646/
User דרור רשף annotated a sentence of MK יצחק וקנין.
The annotated sentence will show in יצחק וקנין page - http://oknesset.org/member/50/
in a special box.
Also רפי רשף's remark will show on the side.

**Comment by RobotnickIsrael** [comment]
I'll start working on it. I'm a begginer so it will take a while :P
