### ISSUE TITLE
Add some fields like average_weekly_presence_hours to member's API

### ISSUE THREAD

**Issue by antin** [hasadna/Open-Knesset#280]
User expected to use the export button for checking data like  average_weekly_presence_hours,mmms_count,bills_stats_first,bills_stats_proposed
those fields not appears using the link of the export button:
https://oknesset.org/api/v2/member/?&format=csv&limit=0
but they appears in the particular member's API like:
https://oknesset.org/api/v2/member/864/?&format=csv&limit=0

Thanks, Alon

**Comment by daonb** [comment]
related to #320
