### ISSUE TITLE
Add person job titles

### ISSUE THREAD

**Issue by OriHoch** [hasadna/Open-Knesset#295]
Should allow to track Person's job titles.

For example, id you go to יולי אדלשטיין in the knesset website (http://www.knesset.gov.il/mk/heb/mk.asp?mk_individual_id_t=1) - under the פעילות בכנסת tab you can see his roles:
תפקידים בנשיאות הכנסת
כנסת 15	סגן יושב-ראש הכנסת
כנסת 16	סגן יושב-ראש הכנסת
כנסת 17	סגן יושבת-ראש הכנסת
כנסת 19	יושב-ראש הכנסת*

We should reflect this in Open Knesset as well.

Should add a table that specifies: person_id, start_time, end_time, job_title
so that we can know at a specific date what's the job title for a person. If there is no end_date then we know it is the current job.

It should not be limited only for MKs but for any person.

Following is a suggested development workflow:

1. Create the model
2. Scrape the data from knesset website (check with @daonb - he wrote a scraper that does it) - prefer to write the scraper using https://github.com/hasadna/okscraper-django - talk with @OriHoch about it.
3. Display the current job title for person's on the website (for example on the MK page)
4. Display historical data as well.

**Comment by daonb** [comment]
Person app has a Role model just for that.

**Comment by daonb** [comment]
As the data about gov roles is already parsed and stored in `Role` models by the `update_gov_roles` command, this is a UI change and should be done as part of #345
