### ISSUE TITLE
Widen Auto-Complete Dropdown in the "Attach Vote" Boxes in Bill Pages

### ISSUE THREAD

**Issue by Tudmotu** [hasadna/Open-Knesset#297]
The autocomplete dropdown that display in the Bill page when trying to link a vote, is very narrow and hard to work with.

Maybe it should be wider?
![image](https://cloud.githubusercontent.com/assets/506487/5462116/95e49664-8579-11e4-9e26-3c7a4cef5417.png)

(if so, can I claim this?)

**Comment by daonb** [comment]
@ofri can you close this?

**Comment by habeanf** [comment]
This issue no longer exists, must have been fixed
