### ISSUE TITLE
Adgenda graphs are stuck at loading data

### ISSUE THREAD

**Issue by guysoft** [hasadna/Open-Knesset#299]
If you open the adgenda pages, where a graph is expected a message "טוען נתונים..." is shown and stuck.
Example link:
https://oknesset.org/agenda/74

Screenshot:
![Image of failure to load](http://i.imgur.com/mtUPhlb.png)

Tested on Firefox 34 and Chromium 39.0.2171.65 Ubuntu 14.10

**Comment by shayh** [comment]
submitted a pull request:
https://github.com/ydaniv/ok-agenda-viz/pull/38
