### ISSUE TITLE
Election candidates cleanup

### ISSUE THREAD

**Issue by OriHoch** [hasadna/Open-Knesset#311]
After the parse_candidates management command runs it might create duplicate persons, for example - אביגדור ליברמן and ליברמן אביגדול
need to go over the persons and merge duplicates

**Comment by daonb** [comment]
The Person admin interface has an action to merge persons so it can be fixed through the admin

**Comment by morchickit** [comment]
And where is the dataset I need to clean? Link please?

**Comment by morchickit** [comment]
@OriHoch - link to where we need to look please?
