### ISSUE TITLE
Add api to get all members detailed data

### ISSUE THREAD

**Issue by brafdlog** [hasadna/Open-Knesset#320]
Currently it isn't possible to get detailed information for multiple members or parties in one call.
I want to get detailed data for all the members and parties.
Calling get on the members path returns only basic information so I am forced to loop over each member and call get on that specific member, but that causes an exception of too many requests.
Can you add a parameter to the get members and get parties apis that will return the detailed data for all members/parties instead of just the basic data?

**Comment by habeanf** [comment]
@brafdlog we've added data on members

**Comment by brafdlog** [comment]
Thanks!
