### ISSUE TITLE
static assets sometimes don't load (getting 404)

### ISSUE THREAD

**Issue by OriHoch** [hasadna/Open-Knesset#323]
if I click refresh a few times, it seems like 50% chance that some assets won't load

![image](https://cloud.githubusercontent.com/assets/1198854/6255224/262452d6-b7b7-11e4-9f2d-05ce14afe10a.png)

**Comment by OriHoch** [comment]
ori@ori-work-laptop:~$ wget https://oknesset.org/static/js/jquery-1.8.3.min.js.pagespeed.jm.0IhQ85x_cu.js
--2015-02-18 21:46:54--  https://oknesset.org/static/js/jquery-1.8.3.min.js.pagespeed.jm.0IhQ85x_cu.js
Resolving oknesset.org (oknesset.org)... 176.34.229.160, 2a01:578:3::b022:e5a0
Connecting to oknesset.org (oknesset.org)|176.34.229.160|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 93583 (91K) [application/javascript]
Saving to: ‘jquery-1.8.3.min.js.pagespeed.jm.0IhQ85x_cu.js.1’

100%[=========================================================================================================================================>] 93,583       192KB/s   in 0.5s   

2015-02-18 21:46:55 (192 KB/s) - ‘jquery-1.8.3.min.js.pagespeed.jm.0IhQ85x_cu.js.1’ saved [93583/93583]

ori@ori-work-laptop:~$ wget https://oknesset.org/static/js/jquery-1.8.3.min.js.pagespeed.jm.0IhQ85x_cu.js
--2015-02-18 21:46:55--  https://oknesset.org/static/js/jquery-1.8.3.min.js.pagespeed.jm.0IhQ85x_cu.js
Resolving oknesset.org (oknesset.org)... 176.34.229.160, 2a01:578:3::b022:e5a0
Connecting to oknesset.org (oknesset.org)|176.34.229.160|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-02-18 21:46:56 ERROR 404: Not Found.

ori@ori-work-laptop:~$ wget https://oknesset.org/static/js/jquery-1.8.3.min.js.pagespeed.jm.0IhQ85x_cu.js
--2015-02-18 21:46:58--  https://oknesset.org/static/js/jquery-1.8.3.min.js.pagespeed.jm.0IhQ85x_cu.js
Resolving oknesset.org (oknesset.org)... 176.34.229.160, 2a01:578:3::b022:e5a0
Connecting to oknesset.org (oknesset.org)|176.34.229.160|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 93583 (91K) [application/javascript]
Saving to: ‘jquery-1.8.3.min.js.pagespeed.jm.0IhQ85x_cu.js.2’

100%[=========================================================================================================================================>] 93,583       199KB/s   in 0.5s   

2015-02-18 21:46:59 (199 KB/s) - ‘jquery-1.8.3.min.js.pagespeed.jm.0IhQ85x_cu.js.2’ saved [93583/93583]

**Comment by habeanf** [comment]
It's because page speed isn't enabled on both servers.

Will talk to meir about it

**Comment by MeirKriheli** [comment]
For now disabled mod_pagespeed on both servers.
