### ISSUE TITLE
Update Member and Person facebook link

### ISSUE THREAD

**Issue by daonb** [hasadna/Open-Knesset#331]
Below is a table we got from Hakikar with facebook links. We need to update `Member` and when no member, find or create a `Person` based on the name. Polyorg is depracted :-(
https://drive.google.com/file/d/0B1rAe9zy7m-PU2hjY3c2QU1BbGgwYXR0VnpxdTFQck1WclVN/view?usp=sharing

**Comment by morchickit** [comment]
Cant we get this from Kikar Hamedina?  @OriHoch @yotammanor

**Comment by yotammanor** [comment]
@morchickit We have script that updates Facebook Pages from Kikar.

**Comment by morchickit** [comment]
Good, thought so! Closing it!
