### ISSUE TITLE
update member - party relationship for knesset 20

### ISSUE THREAD

**Issue by OriHoch** [hasadna/Open-Knesset#341]
members of knesset 20 should have current part field pointing to the party at knesset 20

currently they have party at knesset 19, or no party..

this can be done manually - in the admin - search for member name - edit - change current party field - save

or - can write a script to do it (maybe even from django shell)

**Comment by daonb** [comment]
I've updated the `current_party` and the site shows now 100 MKs.
Seems like there were only 100 MKs in the system:

  >>> Membership.objects.filter(party__knesset__id=20).count() 
  100

Any ideas?

**Comment by OriHoch** [comment]
there are MKs which don't have any value in current_party field

and also some that don't belong to a party

(if current_party field is set - still need to set relation to party object separately..)

:disappointed:

**Comment by OriHoch** [comment]
examples:

party without all mk relations: https://oknesset.org/admin/mks/party/32/

mk without current_party relation: https://oknesset.org/admin/mks/member/941/

there is some code that does those relations but it might need some adjustments to work with knesset 20

**Comment by OriHoch** [comment]
I updated everything manually
