### ISSUE TITLE
Change google auth to OAuth 2.0 (OAuth 1.0 is no longer supported)

### ISSUE THREAD

**Issue by habeanf** [hasadna/Open-Knesset#353]
When trying to use google auth to login, redirected to this page:
https://support.google.com/a/answer/6224347?p=oauth&rd=1

**Comment by habeanf** [comment]
When trying to use google auth to login, redirected to this page:
https://support.google.com/a/answer/6224347?p=oauth&rd=1

**Comment by OriHoch** [comment]
Seems like this doesn't require any code change, only configuration

relevant links:
http://psa.matiasaguirre.net/docs/backends/google.html#google-oauth2
https://developers.google.com/identity/protocols/OAuth_ref#migration

**Comment by daonb** [comment]
I have an `oknesset` project is my google console, but it doesn't look like we're using it.

@ofri you probably have to help us

**Comment by habeanf** [comment]
So apparently this is not the issue we thought it was, because we don't even have oauth 1.0 configured.
I assume we redirect to an oauth 1.0 endpoint and get the deprecation notice before the api sees an empty key/token. Closing this, opened #359 to add google oauth2.0
