### ISSUE TITLE
Add agenda's data to the bill's API

### ISSUE THREAD

**Issue by antin** [hasadna/Open-Knesset#372]
Hi,

I need to see the agenda's data to the bill's API page as it's appears in the bill page. 

Thanks,
Alon

**Comment by otadmor** [comment]
i am working on it.
currently i have no permission to push my changes. will be pushed asap :-)

ofir.

**Comment by habeanf** [comment]
@otadmor Please open a merge request (MR)

**Comment by habeanf** [comment]
@otadmor Also, please reference this issue in the commit

**Comment by OriHoch** [comment]
@otadmor @DanaOshri
Are you working on it?
Please update regarding status of this issue, thanks.

**Comment by otadmor** [comment]
My changes have been pushed to the Sadna's tree from my tree about a month ago.

**Comment by OriHoch** [comment]
Great, thanks
