### ISSUE TITLE
Missing MK's in committees pages

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#384]
In the Aliya Committee, Open Knesset shows 7 parliament members, while there are 9 on the Knesset website. In addition, Robert Ilatov, who is not part of the committee is shown as a part of the committee. http://main.knesset.gov.il/Activity/committees/Immigration/Pages/CommitteeMembers.aspx
compare to - 
https://oknesset.org/committee/3/

@OriHoch - any idea why this is happening? Having false data in the committees is really not good.

**Comment by OriHoch** [comment]
fixed, there was a task needed to run manually

I'll open a new issue to have this task run automatically
