### ISSUE TITLE
Can't add lobbyist to committee protocols

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#386]
הלוביסטית נמצאת בפרוטוקול, אך לא ניתן להוסיפה ידנית:
לוביסט (ברדוגו יועצים), מייצג את פורום כפרי נוער ופנימיות

ויאולטה קורוטין

https://oknesset.org/committee/meeting/10034/

**Comment by OriHoch** [comment]
she is not a lobbyist.. the protocol on our site is a bit confusing after knesset changed their word format

if you look in the original doc - you can see she is without a title, the lobbyist is matan, above her..

http://fs.knesset.gov.il/20/Committees/20_ptv_311209.doc
