### ISSUE TITLE
Remove the following committees from the 20th Knesset

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#388]
הוועדה המשותפת לנושא סביבה ובריאות
ועדה מיוחדת לדיון בהצעת החוק בעניין השוויון בנטל בשירות הצבאי, בשירות האזרחי ובשוק העבודה ולהסדרת מעמדם של תלמידי הישיבות
ועדה מיוחדת לבעיית העובדים הזרים

**Comment by OriHoch** [comment]
will be fixed in #390
