### ISSUE TITLE
Add new committees 

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#390]
הוועדה המיוחדת לדיון בהצעת חוק השידור הציבורי (תיקון), התשע"ה-2015
הוועדה המיוחדת לדיון בהצעת חוק הרשות הממשלתית להתחדשות עירונית
הוועדה המיוחדת ליישום הנגשת המידע הממשלתי ועקרונות שקיפותו לציבור

**Comment by OriHoch** [comment]
I will fix for first 2 committees, regarding the last one - 

הוועדה המיוחדת ליישום הנגשת המידע הממשלתי ועקרונות שקיפותו לציבור
- committee didn't publish any protocols yet (ironic...) and our automatic process depends on protocols to add the committee. as soon as they will have some protocols the committee should appear

**Comment by OriHoch** [comment]
after fix is merged, need to see if committees displayed are correct and update if necessary..
