### ISSUE TITLE
Can't add Eli Cohen (MK) to committee meetings

### ISSUE THREAD

**Issue by shevyk** [hasadna/Open-Knesset#391]
Trying to add Eli Cohen to  https://oknesset.org/committee/meeting/10124/
leads to
משהו השתבש!

משהו שעשית גרם לשגיאה בשרת שלנו. אבל הי! אנחנו לא מאשימים אותך. להפך. עזרת לנו למצוא באג, והצוות שלנו יתפנה מייד לטפל בו. אז תודה רבה לך!

probably because there are two Eli Cohens.

**Comment by morchickit** [comment]
Same with ישראל כץ....

**Comment by noamelf** [comment]
Fix!

**Comment by morchickit** [comment]
Still Can't add him :-( 
ועדת הכספים

**Comment by morchickit** [comment]
I also can't add יהושע זוהר as a lobbyist!

**Comment by OriHoch** [comment]
deployed, looks like bug still occurs

**Comment by alonisser** [comment]
checking



Twitter:@alonisser <https://twitter.com/alonisser>
LinkedIn Profile <http://www.linkedin.com/in/alonisser>
Facebook <https://www.facebook.com/alonisser>
*Tech blog:*4p-tech.co.il/blog
*Personal Blog:*degeladom.wordpress.com
Tel:972-54-6734469

**Comment by alonisser** [comment]
Some bug merge, my code isn't there. checking where is it exactly.. :(

**Comment by alonisser** [comment]
partially isn't there..

**Comment by OriHoch** [comment]
deployed, looks like it's fixed this time :+1:
