### ISSUE TITLE
Missing protocol for committee

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#392]
https://oknesset.org/committee/meeting/9868/

**Comment by OriHoch** [comment]
there were only 5 such meetings without protocol text, some of them from 2014.. so I just fixed it manually

these are the meetings:
https://oknesset.org/committee/meeting/10043/
https://oknesset.org/committee/meeting/9868/
https://oknesset.org/committee/meeting/9646/
https://oknesset.org/committee/meeting/9647/
https://oknesset.org/committee/meeting/8918/

I will open a new issue for a long-term solution, to prevent these bugs from occuring in the future
