### ISSUE TITLE
Not able to approve or reject suggestions in the suggestion feature

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#402]
Can't delete or resolve any suggestion...

**Comment by OriHoch** [comment]
it works for me, please be more specific - about what you are doing and what happens.

**Comment by morchickit** [comment]
אני לוחצת על "אשר" או "דחה" וזה לא עושה כלום...
(משתשמת בכרום על המק)

**Comment by morchickit** [comment]
Working now!
