### ISSUE TITLE
Quarterly QA for bill drafts

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#405]
Currently some bill drafts are linked to the wrong bills. Need to make sure they are connected to right bill number.

**Comment by shevyk** [comment]
Please also create a document detailing the QA methodology.

**Comment by OriHoch** [comment]
@AnatKatz has experience with QA methodology, writing test plans etc.. perhaps she could help. Maybe a meeting of her with @morchickit

**Comment by AnatKatz** [comment]
Sure. @morchickit when can we talk on phone/skype?

**Comment by morchickit** [comment]
I'll be in the next meetup?

**Comment by AnatKatz** [comment]
when is the next meetup?...

**Comment by morchickit** [comment]
Monday. :-)

**Comment by AnatKatz** [comment]
Sent you a mail...

**Comment by morchickit** [comment]
Anat, when?

**Comment by morchickit** [comment]
@OriHoch - did you speak to @ofri about how to get this report from the system?

**Comment by morchickit** [comment]
Same as #447 . Closing.
