### ISSUE TITLE
Some vote are missing on oknesset's site:

### ISSUE THREAD

**Issue by antin** [hasadna/Open-Knesset#407]
Hi,

1. vote name:
"הצעת חוק עסקאות גופים ציבוריים (תיקון - חובת שימוש במסמכים ממוחשבים), התשע"ה-2015"
the vote on the knesset's site: 
http://www.knesset.gov.il/vote/heb/Vote_Res_Map.asp?vote_id_t=22065
the vote not apperar on oknesset's site:
https://oknesset.org/vote/?vtype=all&tagged=all&order=time&from_date=2015-06-23&to_date=2015-06-23

2. vote name:
להעביר את הצעת החוק לוועדה - הצעת חוק מס ערך מוסף (תיקון – מס בשיעור אפס על מוצרי מזון בסיסיים), התשע"ה–2015 
the vote on the knesset's site: 
http://www.knesset.gov.il/vote/heb/Vote_Res_Map.asp?vote_id_t=22259
the vote not apperar on oknesset's site:
https://oknesset.org/vote/?from_date=2015-07-22&tagged=all&vtype=all&order=time&to_date=2015-07-22&page=1

3. vote name:
להעביר את הצעת החוק לוועדה - הצעת חוק ההוצאה לפועל (תיקון – הפטר לחייב), התשע"ה–2015
the vote on the knesset's site: 
http://www.knesset.gov.il/vote/heb/Vote_Res_Map.asp?vote_id_t=22074
the vote not apperar on oknesset's site:
https://oknesset.org/vote/?from_date=2015-06-24&tagged=all&vtype=all&order=time&to_date=2015-06-24&page=1

**Comment by OriHoch** [comment]
@antin  - newer votes are appearing now, but it's possible some votes are still missing, so leaving this issue open..

**Comment by OriHoch** [comment]
all the votes seems to be updated now, but the voting scraper should be improved

**Comment by AnatKatz** [comment]
@antin 
How did you catch this bug?

**Comment by morchickit** [comment]
Added to #463 . Closing this.
