### ISSUE TITLE
Future votes are not tagged with old bills tags

### ISSUE THREAD

**Issue by otadmor** [hasadna/Open-Knesset#409]
The following scenarios will not have the same result:
first scenario:
1) adding a bill
2) tagging a bill
3) adding a "first vote" to the bill
4) will result in the first vote not being tagged

Second scenario:
1) adding a bill
2) adding a "first vote" to the bill
3) tagging a bill
4) will result in the first vote being tagged

See test in auxiliary/test.py:TagVoteBillTagOrderTest in my clone.

**Comment by otadmor** [comment]
Probably the next change is needed:
[code]
def add_tags_to_bill_related_objects(sender, instance, **kwargs):
    bill_ct = ContentType.objects.get_for_model(instance)
    for ti in TaggedItem.objects.filter(content_type=bill_ct, object_id=instance.id):
        add_tags_to_related_objects(sender, ti, **kwargs)
post_save.connect(add_tags_to_bill_related_objects, sender=Bill)
[/code]

it seem to be working, but it wasnt tested with bills tests.

**Comment by OriHoch** [comment]
fixed and deployed
