### ISSUE TITLE
Fix requirement.txt file

### ISSUE THREAD

**Issue by yotamsha** [hasadna/Open-Knesset#410]
django-debug-toolbar>=1.0 should be django-debug-toolbar==1.0

**Comment by habeanf** [comment]
Why?

**Comment by yotamsha** [comment]
It seems that in later version of django-debug-toolbar (1.4) there is a requirement which isn't compatible with django 1.6.11 , only with 1.7 (https://docs.djangoproject.com/en/1.8/ref/utils/#module-django.utils.module_loading).
This caused an error when trying to import the "import_string" lib.
