### ISSUE TITLE
Searching "כנסת פתוחה" in google gives a link to the 19th knesset, and not to the 20th knesset

### ISSUE THREAD

**Issue by otadmor** [hasadna/Open-Knesset#412]
See the Image.
![knesset19](https://cloud.githubusercontent.com/assets/12109912/10593303/37bbad36-76cb-11e5-99c0-e273d60b1992.png)

**Comment by OriHoch** [comment]
#414 should fix it, also I demoted the knesset 19 link in google sitelinks, so that should help as well

it's not related to 19th knesset having no end date
