### ISSUE TITLE
The 19th knesset has no end date in the database

### ISSUE THREAD

**Issue by otadmor** [hasadna/Open-Knesset#413]
Currently, only the start_data is initialized for the 19th knesset, and the end_date is defined in the 18th knesset only.

This might give us wrong results with date based queries / migration, such as tag detail for a certain knesset.

Might be related to https://github.com/hasadna/Open-Knesset/issues/412.

**Comment by OriHoch** [comment]
looks like we don't use the knesset end_date anywhere in the code

however, I added it manually..
