### ISSUE TITLE
Fix Aiman Uda picture on his MK page. 

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#425]
Current looks as follows - 
https://oknesset.org/member/938/%D7%90%D7%99%D7%99%D7%9E%D7%9F-%D7%A2%D7%95%D7%93%D7%94/

Knesset picture link - http://www.knesset.gov.il/mk/images/members/Odeh_Aiman.jpg

@OriHoch , @noamelf - Can someone fix it before tomorrow? Or show me how to replace it in the code base? I could not find it. 

Thanks!

**Comment by OriHoch** [comment]
I'm on it

**Comment by OriHoch** [comment]
fixed (there is caching so it might take a few minutes until you will see the update)

https://oknesset.org/member/938/%D7%90%D7%99%D7%99%D7%9E%D7%9F-%D7%A2%D7%95%D7%93%D7%94/?x=y
