### ISSUE TITLE
the swagger link in docs is broken

### ISSUE THREAD

**Issue by daonb** [hasadna/Open-Knesset#426]
this [doc](https://github.com/hasadna/Open-Knesset/blame/master/docs/api/source/api_v2/swagger.rst) links to [here](https://oknesset.org/api/v2/doc/) which is broken

**Comment by OriHoch** [comment]
fixed swagger in 4552ed51e8b3561a8a9219b5e2ada3a572230071

**Comment by OriHoch** [comment]
fixed
https://oknesset.org/api/v2/doc/
