### ISSUE TITLE
The 4 hakim that do not appear on site 

### ISSUE THREAD

**Issue by AnatKatz** [hasadna/Open-Knesset#429]
1. http://www.knesset.gov.il/mk/heb/mk.asp?mk_individual_id_t=950
2. http://www.knesset.gov.il/mk/heb/mk.asp?mk_individual_id_t=952
3. http://www.knesset.gov.il/mk/heb/mk.asp?mk_individual_id_t=879
4. http://www.knesset.gov.il/mk/heb/mk.asp?mk_individual_id_t=899

Note that they are all " (תקופת כהונה חלקית)"

**Comment by OriHoch** [comment]
all four were added
