### ISSUE TITLE
update MKs details - add new MKs, remove old, update start_date

### ISSUE THREAD

**Issue by OriHoch** [hasadna/Open-Knesset#430]
There were many changes in MKs (MKs were replaced), need to update the MKs list - go over the list here: https://oknesset.org/parties-members/20/ - and write-up required changes - add / remove MKs

also, for each MK the start / end date of term should be updated

**Comment by noamelf** [comment]
Possible duplicate #429

**Comment by OriHoch** [comment]
required output of this task: 
* list of required changes
* or, even better - fix it in the admin

**Comment by RacheliRoval** [comment]
הי חברים,
אז אלו השינויים הנדרשים:
1. הליכוד- צריך להוסיף את ח"כ שרן השכל. נכנס ב-27.8.2015 (במקום דני דנון  שהוסר מהרשימה)
 2.הבית היהודי- להוסיף את שולי מועלם רפאלי. נכנסה ב-9.10.2015  במקום נפתלי בנט
אבי וורצמן- החליף את ינון מגל בין ה-3.12.2015 ל- 6.12.2015.
נפתלי בנט- החליף את אבי וורצמן החל מה-6.12.2015.
3. המחנ"צ- צריך להוסיף את ח"כ יעל כהן פארן. נכנסה ב-25.11.2015 במקום ח"כ דניאל עטר שהוסר מהרשימה.
4. יש עתיד- להוסיף את ח"כ אלעזר שטרן. נכנס ב-4.9.2015 במקום שי פירון שהוסר מהרשימה.
5. ישראל ביתנו- להוסיף את ח"כ עודד פורר. נכנס ב-4.9.2015 במקום שרון גל שהוסר מהרשימה.

**Comment by OriHoch** [comment]
DONE
