### ISSUE TITLE
Attendance at Knesset numbers are incorrect

### ISSUE THREAD

**Issue by shevyk** [hasadna/Open-Knesset#434]
attendance numbers for all MKs are currently zero., e.g. https://oknesset.org/member/860/%D7%A7%D7%90%D7%A8%D7%99%D7%9F-%D7%90%D7%9C%D7%94%D7%A8%D7%A8/

נוכחות במשכן

**Comment by AnatKatz** [comment]
Also 
https://oknesset.org/member/864/%D7%A0%D7%A4%D7%AA%D7%9C%D7%99-%D7%91%D7%A0%D7%98/

https://oknesset.org/member/915/%D7%9E%D7%99%D7%A8%D7%91--%D7%91%D7%9F-%D7%90%D7%A8%D7%99/

https://oknesset.org/member/200/%D7%90%D7%99%D7%9C%D7%9F-%D7%92%D7%99%D7%9C%D7%90%D7%95%D7%9F/

**Comment by morchickit** [comment]
See here - 
![screen shot 2016-02-22 at 20 14 25](https://cloud.githubusercontent.com/assets/3273659/13227830/4148d386-d9a1-11e5-9462-74c8c3e49d46.png)

**Comment by OriHoch** [comment]
@morchickit - your previous comment is about a different bug

this issue is about presence at knesset displayed on MK page

looks like presence at knesset data is correct now, closing this bug
