### ISSUE TITLE
Bug in counting votes in Plenum

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#436]
In this plenum vote, Open Knesset present the result as 29-46. - 
https://oknesset.org/vote/9086/

The Knesset website show a different result - 47 - 30 - http://www.knesset.gov.il/vote/heb/Vote_Res_Map.asp?vote_id_t=23556

Why is the difference?

**Comment by OriHoch** [comment]
there were missing MKs which we didn't count: שרן השכל and עודד פורר

these MKs were added today, I will check if we need to re-run the votes processing

**Comment by OriHoch** [comment]
I'm now running a process which goes over past votes and updates them as well
