### ISSUE TITLE
Protocols in committees are not up to date. 

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#444]
In ועדת הכלכלה, in Oknesset the last protocol is from 14/10/15.
https://oknesset.org/committee/2/

In the Knesset website is from 8/12/15:
http://main.knesset.gov.il/Activity/Committees/Economics/Pages/CommitteeProtocols.aspx

**Comment by morchickit** [comment]
Any updates? @noamelf

**Comment by noamelf** [comment]
@morchickit hi, I'm working on the votes thing, if there will be a connection I'll update...

**Comment by morchickit** [comment]
OK, this is becoming top of the top priorities. We have two months of missing protocols. @OriHoch - for you attention as well.

**Comment by OriHoch** [comment]
I'm working on it

**Comment by OriHoch** [comment]
will be handled in #490
