### ISSUE TITLE
Delete the DOCTYPE header in committees protocols 

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#448]
Each committee protocol start with the lines - 
<!DOCTYPE book PUBLIC "-//OASIS//DTD DocBook XML V4.1.2//EN"
"http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dt

This needs to be removed from the display in each committee. Example for a protocol - 
https://oknesset.org/committee/meeting/10458/

**Comment by OriHoch** [comment]
will be handled in #490
