### ISSUE TITLE
Fix the voting data of (הצעת חוק השידור הציבורי (תיקון מס' 2

### ISSUE THREAD

**Issue by RacheliRoval** [hasadna/Open-Knesset#449]
בהצעת חוק השידור הציבורי (תיקון מס' 2) יש טעות בנתוני ההצבעה: בבעד חסרה ח"כ שרן השכל ובנגד  יש את ח"כ קרין אלהר למרות שלא הייתה בהצבעה.
![2015-12-14 - knesset](https://cloud.githubusercontent.com/assets/16195243/11793311/843ebb30-a2b3-11e5-8f3f-744e687ae252.jpg)

**Comment by morchickit** [comment]
@OriHoch - didn't we ran an algorithm to detect this last week?

**Comment by morchickit** [comment]
@OriHoch - is this the same as #407 ?

**Comment by OriHoch** [comment]
no, it's a different problem, here the vote appears but some MKs are missing

@noamelf  - this is a reason to reparse vote members, even if we already have the vote

**Comment by OriHoch** [comment]
I'm working on it

**Comment by OriHoch** [comment]
there were 13 votes with this problem, not sure where they came from.. I fixed them manually

I also did a minor fix to votes_scraper which should prevent this from happening in the future

**Comment by OriHoch** [comment]
there are still a lot of problems with votes scraped with the old scraper. This will be handled in issue #547
