### ISSUE TITLE
Add government bills to Open Knesset

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#452]
This is an issue to all of the problems with gov bills in Open Knesset. 

- [x] Mark bills as gov bills 
- [x] Mark private bills as private
- [x] Mark Knesset bills as Knesset
- [ ] Allow assignment of gov bills to committees and votes.

**Comment by morchickit** [comment]
@OriHoch and @noamelf - @RacheliRoval worked to see how these bills looks in the app and from content wise, it is a mess. We need to do some code archeological digging understand the flow of governmental bill vs. knesset bill vs. private bill in order to proceed here.

**Comment by OriHoch** [comment]
bills are marked as gov bills, for example: https://oknesset.org/bill/7447/
![image](https://cloud.githubusercontent.com/assets/1198854/11939742/cb0f3390-a82c-11e5-8051-3d6b0509c3fb.png)

**Comment by morchickit** [comment]
So - we need to remove קריאה טרומית from government bills as well. 
Need to mark in this page what bill is private and what is governmental - https://oknesset.org/bill/

**Comment by morchickit** [comment]
Another example to the problems with gov bills - 
n the bills page  https://oknesset.org/bill/ the bill 
חוק לתיקון פקודת הסטטיסטיקה מס` 4
is marked in Va'ada while in the bill page - https://oknesset.org/bill/9601/ - nothing is marked.

**Comment by OriHoch** [comment]
I think most of the stuff will be fixed when v2.4.0 is deployed (which should be today)

Following changes were made:

* show the bill type both in the bill list page, and in bill detail page
* allow to filter bills according to type
* fix the problem with government bill stage

**Comment by OriHoch** [comment]
closing this issue, please open new one if more work is needed

**Comment by morchickit** [comment]
go for it.
