### ISSUE TITLE
Bills- add header above the images of the MK's 

### ISSUE THREAD

**Issue by RacheliRoval** [hasadna/Open-Knesset#460]
it is not clear who the people in the pictures are. 
we need to explain those are the MK's who initiated the law (יוזמי החוק)
![image](https://cloud.githubusercontent.com/assets/16195243/11938681/25e13cf8-a825-11e5-8344-b8e310e821d0.png)

**Comment by morchickit** [comment]
Easy - add header - יוזמי החוק between the name of the bills and  MK's pictures.

**Comment by OriHoch** [comment]
deployed, looks good
