### ISSUE TITLE
missing votes in website

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#463]
See this forum discussion - http://forum.hasadna.org.il/t/topic/1092

**Comment by morchickit** [comment]
Adding #407 to this tasks to avoid double work.

**Comment by OriHoch** [comment]
@noamelf - I'm going to kidnap this issue from you..

**Comment by noamelf** [comment]
I guess that's a good idea...

On Mon, Feb 8, 2016, 9:56 PM Ori Hoch <notifications@github.com> wrote:

> @noamelf <https://github.com/noamelf> - I'm going to kidnap this issue
> from you..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hasadna/Open-Knesset/issues/463#issuecomment-181498551>
> .
>
-- 
Noam Elfanbaum
+972-545551680

**Comment by OriHoch** [comment]
AFAIK all votes should appear now.. closing the issue and will open new one for testing
