### ISSUE TITLE
fill-in details about Amir Ohana

### ISSUE THREAD

**Issue by OriHoch** [hasadna/Open-Knesset#464]
Need to edit Amir Ohana in admin and add some details about him

https://oknesset.org/member/953/%D7%90%D7%9E%D7%99%D7%A8-%D7%90%D7%95%D7%97%D7%A0%D7%94/

**Comment by morchickit** [comment]
Still not updated in the Knesset website... I will give it a week before Updating again.

**Comment by morchickit** [comment]
Added pic. 
No data about committees yet. :-\
