### ISSUE TITLE
Committies- there is no member list in ועדת שקיפות

### ISSUE THREAD

**Issue by RacheliRoval** [hasadna/Open-Knesset#472]

**Comment by morchickit** [comment]
Let's add it manually. @OriHoch - is it fine by you?

**Comment by OriHoch** [comment]
sure

**Comment by RacheliRoval** [comment]
Can I do it or I need special permission?

**Comment by morchickit** [comment]
You do need permissions, and you can do it if you want to. @OriHoch or @noamelf can you give Racheli permissions?

**Comment by noamelf** [comment]
Sure let's do it in the next meeting

On Tue, Dec 29, 2015, 12:52 PM morchickit <notifications@github.com> wrote:

> You do need permissions, and you can do it if you want to. @OriHoch
> <https://github.com/OriHoch> or @noamelf <https://github.com/noamelf> can
> you give Racheli permissions?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hasadna/Open-Knesset/issues/472#issuecomment-167764402>
> .
>
-- 
Noam Elfanbaum
+972-545551680

**Comment by RacheliRoval** [comment]
I added the members to the committee. we can close the task now. 
thank you @noamelf :)

**Comment by noamelf** [comment]
:)

On Wed, Jan 6, 2016 at 10:36 AM RacheliRoval <notifications@github.com>
wrote:

> I added the members to the committee. we can close the task now.
> thank you @noamelf <https://github.com/noamelf> :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hasadna/Open-Knesset/issues/472#issuecomment-169266856>
> .
>
-- 
Noam Elfanbaum
+972-545551680
