### ISSUE TITLE
Bug- ועדה מיוחדת להתחדשות עירונית

### ISSUE THREAD

**Issue by RacheliRoval** [hasadna/Open-Knesset#473]
בלשונית "ועדות" מופיעות שתי ועדות ששמן כמעט זהה:
"ועדה מיוחדת לדיון בהצעת חוק הרשות הממשלתית להתחדשות עירונית, התשע"ה-2015" *. 
הוועדה המיוחדת לדיון בהצעת חוק הרשות הממשלתית להתחדשות עירונית ובסעיפים מהצעת חוק התכנית הכלכלית"*
צריך להבין מאיפה נובעת הכפילות.
  בועדה הראשונה- יש רשימת חברים לא מעודכנת, אין ישיבות קרובות (למרות שבאתר הכנסת יש) אין ישיבות שטרם פורסם פרוטוקול ויש רק שני פרוטוקלים מיולי ואוגוסט 2015.
בועדה השניה- אין רשימת חברים בכלל, אין ישיבות קרובות אבל יש ישיבות מהן טרם פורסם פרוטוקול ויש פרוטוקולים  שלא מופיעים בועדה הראשונה  מהחודשים ספטמבר- אוקטובר 2015.

באתר הכנסת אין פרוטוקולים בכלל של הועדה אלא רק ישיבות מתוכננות.

בכל אופן, בשלב ראשוני חשוב לאחד בין הועדות ולדאוג שלא תהיה כפילות.

**Comment by morchickit** [comment]
This is still going on. @OriHoch - Can I fix it manually or do you need to work on this?

**Comment by morchickit** [comment]
OK - there are two committees in the same name in the DB, and therefore the confusion. @OriHoch should I just delete one of them? It looks like this one is the faulty one- no committee members in the db - https://oknesset.org/admin/committees/committee/33/

**Comment by OriHoch** [comment]
I hid that committee (checked the "hide" checkbox in the committee admin)

**Comment by OriHoch** [comment]
about the meetings - there is currently a bug preventing scraping of meetings of this specific committee (https://github.com/hasadna/knesset-data/issues/16) Once that bug is fixed we should have the committee meetings.

**Comment by OriHoch** [comment]
this will be fixed in #534
