### ISSUE TITLE
חוק שהוצע מוועדת כנסת לא מופיע באתר כנסת פתוחה‎ 

### ISSUE THREAD

**Issue by antin** [hasadna/Open-Knesset#479]
חוק שיו"ר ועדת הכנסת הציע לא מופיע‎
http://knesset.gov.il/laws/data/billknesset/608/608.pdf
ולא קיים ב -8-12-2015
באתר כנסת פתוחה
https://oknesset.org/bill/?&page=5

@morchickit 
תוכלי לתעדף?

תודה,
אלון

**Comment by morchickit** [comment]
הבאג הזה כבר מוכר ובדיוק דיברתי איתו עכשיו עם @noamelf
https://github.com/hasadna/Open-Knesset/issues/468

סוגרת את זה. :-)
