### ISSUE TITLE
Add help text of date format

### ISSUE THREAD

**Issue by dror-kris** [hasadna/Open-Knesset#480]
תוכן: בעת הכנסת תאריכים, אני מתבקש להכניס תאריך חוקי, ולא כתוב מה זה.. (פורמט של השדה או הגבלה על שנים המצוייות במאגר)

Not sure where they are talking about...

**Comment by morchickit** [comment]
@dror-kris - I don't follow, did they give an example where it's happening?

**Comment by dror-kris** [comment]
I also am not sure, I tried to find on the site what they were referring to - i thought maybe you knew :/

**Comment by morchickit** [comment]
I have no clue. I will re-open when we know.
