### ISSUE TITLE
Update members list of the different committees 

### ISSUE THREAD

**Issue by RacheliRoval** [hasadna/Open-Knesset#492]

**Comment by RacheliRoval** [comment]
@morchickit , what did you tell me about ועדת הכספים?
It is full of MK's which are actually not members:
שלי יחימוביץ, יצחק כהן, יעקב ליצמן, איוב קרא, חיים כץ, גילה גמליאל

**Comment by RacheliRoval** [comment]
@morchickit, can I remove  דרעי, אלקין, גלאון, לוין, גפני ואילטוב 
מועדת חוץ וביטחון?

**Comment by morchickit** [comment]
ליצמן, דרעי, לוין וגמליאל הם שרים, לכן הם לא חברי ועדה. 
אפשר להוציא

**Comment by morchickit** [comment]
בואי נשאיר את השאר בינתיים

**Comment by OriHoch** [comment]
this will be fixed in #534
