### ISSUE TITLE
Add latest Facebook statuses to homepage

### ISSUE THREAD

**Issue by yotammanor** [hasadna/Open-Knesset#494]
from Hasadna's project kikar-hamedina ( www.kikar.org , https://github.com/hasadna/kikar-hamedina)

**Comment by morchickit** [comment]
All for it!
@yotammanor - sounds good!

**Comment by yotammanor** [comment]
@OriHoch  Is this my responsibility to close this tag, or yours?

**Comment by OriHoch** [comment]
usually whomever opened it should close it
