### ISSUE TITLE
Add the following message to committees home page

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#497]
On the top of this page:
https://oknesset.org/committee/
 
"לתשומת לבכם, המידע על ועדות הכנסת אינו מעודכן, זאת מכיוון שמאגרי המידע הרשמיים של הכנסת, ממנו אנחנו שואבים את המידע, אינם מעודכנים. לקריאה נוספת על כיצד אנחנו משיגים את המידע, לחץ כאן"

**Comment by OriHoch** [comment]
I added an option for an admin to add such messages without changing the code

it uses the flatpages model (דפים פשוטים) - you just need to add a page with:
* url = the url of the page you want to add the message to (in this case = /committee/)
* title = doesn't matter, only for internal book keeping
* content = the message content (can include html)
* optionally - in advanced options you can specify template name to modify how the message will look, available values:
  * "" = default
  * "flatpages/block_error.html" 
  * "flatpages/block_info.html"
  * "flatpages/block_success.html"

**Comment by OriHoch** [comment]
I added the committee message here:
* https://oknesset.org/admin/flatpages/flatpage/7/
displayed on the site:
* https://oknesset.org/committee/

**Comment by OriHoch** [comment]
@morchickit  - assigning to you, please test and edit message if necessary

**Comment by morchickit** [comment]
It looks good. Closing. Will remove it when we fixed most of the bugs in the committee.
