### ISSUE TITLE
הוסף דף תוכן - מקורות מידע

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#498]
Add a page - Website resources - אודות המידע בכנסת פתוחה

אתר כנסת פתוחה אוסף נתונים ממגוון מקורות על מנת להנגיש את המידע לציבור בצורה נוחה ופשוטה. ככל, אנחנו מנסים שרוב המידע לאתר כנסת פתוחה יגיע ממקורות רשמיים של הכנסת. הכנסת מציעה ממשק למפתחים בשם Application Programing Interface, או בקצרה API, שדרכו היא מפרסמת נתונים מהכנסת. לצערנו, ממשק הנתונים כרגע אינו עדכני בכמה מקרים, ולכן לא תוכלו לראות את המידע בכנסת פתוחה. 

עד אוקטובר 2015, היינו מבצעים גירוד של המידע, או Scraping, באנגלית, פעולה אשר הייתה עוברת על דפי אתר הכנסת ומורידה את תוכן המידע בצורה אוטומטית. למרות שפעולה זו מביאה לנו מידע עדכני, היא אינה יעילה מכיוון שצריך להתאים את הקוד שמבצע עבודה זו מספר פעמים בשנה. על כן, אנחנו מנסים כמה שיותר להשתמש במידע הרשמי של הכנסת. לכן, בכמה מקרים לא תוכלו לראות מידע עדכני מאוקטובר 2015 ואילך. 

בנוסף, אתר הכנסת עדיין אינו נותן מידע מסודר על נוכחות חברי כנסת בועדות או אינו מקשר בין חוקים להצבעות וועדות. מידע זה ניתן לכם בכנסת פתוחה על ידי עיבוד המידע על ידינו. אנחנו מנסים לעשותו כך שהוא יהיה כמה שיותר עדכני. אם מצאתם טעות, אנא כתבו לנו…

אם זה מפריע לכם כמו שזה מפריע לנו שלא ניתן למצוא הצבעות מיד לאחר התרחשותן, או שהועדות אינן מעודכנות באתר הכנסת מאז 2014, אתם מוזמנים להתלונן על כך למערכת אתר הכנסת הרשמי בכתובת המייל feedback@knesset.gov.il.

מידע נוסף שתוכלו למצוא בכנסת פתוחה הוא קישור לדפי הרשתות החברתיות של חברי הכנסת. מידע זה מגיע מאתר Kikar , או כיכר המדינה. 

@OriHoch , @noamelf - Comments, additions or ideas to this page? I tried to make it as simple as I can! :-)

**Comment by OriHoch** [comment]
@morchickit - you can add pages yourself in the admin

check it out:
* https://oknesset.org/admin/flatpages/flatpage/1/
* https://oknesset.org/committee/help/

regarding this page - there is already a block in the about page regarding source of the data - so it should probably be updated, or removed and instead show a link to this new page..

**Comment by morchickit** [comment]
Cool! @OriHoch - https://oknesset.org/admin/flatpages/flatpage/6/
now how do we add it to the toolbar?

**Comment by morchickit** [comment]
I am updating the about page, work in progress. :]

**Comment by OriHoch** [comment]
there was a bug with how the page was displayed, fixed now and deployed

**Comment by OriHoch** [comment]
@morchickit  - adding to toolbar will require code change, please open an issue..

**Comment by noamelf** [comment]
@morchickit I'll add it the lower toolbar.

**Comment by morchickit** [comment]
Thank you! :-)

**Comment by noamelf** [comment]
Added to v3.1.0
