### ISSUE TITLE
Add page - Terms of use

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#501]
Add the following content:
- השימוש באתר על אחריות המשתמש בלבד.
אנו משתדלים שהמידע שאנחנו מציגים לכם יהיה אמין ומדויק, אולם אין ביכולתנו להבטיח זאת.
באופן כללי, אל תעשו דברים לא חוקיים או לא נחמדים.
על כל פרסום (מקוון או לא מקוון. לרבות עיתונים, בלוגים, אתרים) המשתמש בנתונים מהאתר, לציין זאת. אם מדובר בפרסום מקוון - עליכם לקשר לאתר כנסת פתוחה. בשום אופן אין ליצור מצג כאילו "כנסת פתוחה" או מי מטעמה מקבל את המסקנות העולות מהניתוח שלכם, או תומך באופן כלשהו בפרשנות שלכם לנתונים. אם לא תעבדו לפי הכללים - נצטרך להקים אתר כזה שיעקב גם אחריכם :)
- זכויות יוצרים
פרויקט "כנסת פתוחה" הוא פרויקט תוכנה חופשית. תוכלו למצוא את קוד המקור כאן .
התוכן המוצג באתר - מידע גולמי על חוקים ופעילות פרלמנטרית - אינו מוגן בזכויות יוצרים.
תמונות הח"כים המוצגות באתר לקוחות מאתר הכנסת, והזכויות עליהן שמורות לבעליהן.
תגובות והארות גולשים מפורסמות ברישיון CC-BY-SA 2.5

**Comment by alonisser** [comment]
Design? where should be displayed? page? modal? something else?

**Comment by morchickit** [comment]
OMG, @alonisser is commenting! :-) Exciting! I think it would be good to add a link to it on the footer, like in any other website. 
@OriHoch - should I add it through Django as a page and then open a task to link to it in the footer?

**Comment by morchickit** [comment]
Content is here - 
https://oknesset.org/terms-of-use/

I have opened a new issue to change the footer (which I also already did).
Closing this.
