### ISSUE TITLE
Add אכרם חסון  and יגאל גואטה to the MK's list

### ISSUE THREAD

**Issue by RacheliRoval** [hasadna/Open-Knesset#503]
מסתבר ששניהם הושבעו בשבוע שעבר בחסות החוק הנורבגי:
אכרם חסון הצטרף לכולנו במקום כחלון (שכבר הוסר מהרשימה)
יגאל גואטה הצטרף במקום משולם נהרי (שמשום מה לא מעודכן ברשימת חברי הכנסת)

**Comment by morchickit** [comment]
משולם נהרי זה גם כולנו?

**Comment by RacheliRoval** [comment]
sorry... הוא בש"ס

**Comment by morchickit** [comment]
אכרם חסון היה בכנסת ה- 18, אז יהיה לנו אותו. הועדות שלו עוד לא מעודכנות - 
http://www.knesset.gov.il/mk/heb/mk.asp?mk_individual_id_t=854
יגאל גואטה - https://github.com/hasadna/Open-Knesset/issues/503

אין שום מידע על משולם נהרי באתר הכנסת...

**Comment by RacheliRoval** [comment]
מוזר... אבל הוא בודאות היה ח"כ עד לפני רגע
look-
![default](https://cloud.githubusercontent.com/assets/16195243/12715050/c119aba2-c8e0-11e5-8540-c804b133dd88.png)

**Comment by RacheliRoval** [comment]
הקטע הרלוונטי נחתך בטעות :)
![default](https://cloud.githubusercontent.com/assets/16195243/12715111/121d11c4-c8e1-11e5-9f07-8dd21a28cedd.png)

**Comment by morchickit** [comment]
לא מצאתי אותו באתר... אני אסתכל יותר מאוחר היום.

**Comment by morchickit** [comment]
OK, updated Akram Hason. 

As I thought, the Knesset didn't update the page for Meshulam Nehari ... See the current page for MK in the Knesset website - 
![screen shot 2016-02-08 at 17 43 44](https://cloud.githubusercontent.com/assets/3273659/12893885/b0430bec-ce8b-11e5-93d9-09c49ed90893.png)

**Comment by morchickit** [comment]
I am updating according to this page, but this is an archive page, not a current page... :-\
http://www.knesset.gov.il/mk/heb/mk.asp?mk_individual_id_t=222

**Comment by morchickit** [comment]
All done. 
Attention @yotammanor !
