### ISSUE TITLE
Vote says none where there are actually votes

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#506]
https://oknesset.org/vote/9344/

**Comment by morchickit** [comment]
![screen shot 2016-02-07 at 23 01 26](https://cloud.githubusercontent.com/assets/3273659/12876011/c1f5f64e-cdee-11e5-85f1-30a82107c373.png)

**Comment by alonisser** [comment]
What does the db show? is it a scraping problem or a logic problem in the site while the db does show the votes? (I don't have access to the db.. :) )

**Comment by morchickit** [comment]
I thought that was fixed on Monday, but when I looked at it now, I see it wasn't fixed. @OriHoch will know what it can be...

**Comment by alonisser** [comment]
No data in DB also 
https://oknesset.org/admin/laws/vote/9344/
Might be a scraping bug? @OriHoch

**Comment by OriHoch** [comment]
there were 13 votes with this problem, not sure where they came from.. I fixed them manually

I also did a minor fix to votes_scraper which should prevent this from happening in the future
