### ISSUE TITLE
Change links in the site's footer

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#509]
Current we have this. 
![screen shot 2016-02-08 at 23 44 24](https://cloud.githubusercontent.com/assets/3273659/12903236/147d831c-cebe-11e5-871e-cdca8ad04ed6.png)

@OriHoch - If you can let me know which file i use to change, I will do it myself. I couldn't find it in templates.

**Comment by morchickit** [comment]
@noamelf - can you guide me here maybe?

**Comment by OriHoch** [comment]
this is the relevant code:
https://github.com/hasadna/Open-Knesset/blob/master/templates/site_base.html#L170

**Comment by morchickit** [comment]
On it!

**Comment by morchickit** [comment]
Dont I need to add new terms here as well? 
https://github.com/hasadna/Open-Knesset/blob/master/locale/he/LC_MESSAGES/django.po

**Comment by morchickit** [comment]
Done. Ori, please check it to see that I didn't messed anything...

**Comment by morchickit** [comment]
OK, it didn't change it in the django.po @OriHoch - what did I do wrong?

**Comment by OriHoch** [comment]
please link to the pull request where the change was done

**Comment by morchickit** [comment]
I assume it is this - https://github.com/hasadna/Open-Knesset/pull/529

**Comment by morchickit** [comment]
All updated!
