### ISSUE TITLE
Fix Alert about MK's that voting different from their peers in Coalition/opposition

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#513]
See this vote - 
![screen shot 2016-02-10 at 18 27 59](https://cloud.githubusercontent.com/assets/3273659/12957332/0cdc9b90-d024-11e5-93c2-336b7c84e03f.png)

In the vote itself, it looks like the opposition all voted the same, yet they are all marked (besides Miki Levi) 
![screen shot 2016-02-10 at 18 29 03](https://cloud.githubusercontent.com/assets/3273659/12957364/38d155e2-d024-11e5-8639-07eb7a3117ae.png)

**Comment by morchickit** [comment]
Happens here- 
https://oknesset.org/vote/9434/

And here - https://oknesset.org/vote/9424/
Here Tzipi Livni and Yael German are marked as coalition...

**Comment by alonisser** [comment]
@morchickit  Can you find an example in the test db so I can debug this?

**Comment by morchickit** [comment]
@alonisser - You assume I have access to the test DB? :-)

**Comment by alonisser** [comment]
yap



Twitter:@alonisser <https://twitter.com/alonisser>
LinkedIn Profile <http://www.linkedin.com/in/alonisser>
Facebook <https://www.facebook.com/alonisser>
*Tech blog:*4p-tech.co.il/blog
*Personal Blog:*degeladom.wordpress.com
Tel:972-54-6734469

**Comment by morchickit** [comment]
I guess you mean this? 
https://oknesset.org/admin/laws/vote/9434/

**Comment by alonisser** [comment]
any example maybe in the under 8000 (id number) votes? scraping on my computer to get to 9434 takes hooorrrrsssss

**Comment by morchickit** [comment]
Oh, that would be a challenge. I think this happens only on the the 20th Knesset...

**Comment by alonisser** [comment]
ok.. I'll let the scraping run for the night. hopefully until I need to go to work we'll pass the magic number

**Comment by morchickit** [comment]
Lucky you! I found one - https://oknesset.org/vote/7923/
It's from the 19th Knesset. I guess the code doesn't know how to deal when we switch members from opposition to coalition

**Comment by morchickit** [comment]
Oh, wait, actually, in this bill it is right - Haredi, in the opposition are voting with the Coalition, and coalition is voting with the opposition.

**Comment by alonisser** [comment]
If the issues is switching members from opposition to coalition then this would get messy solving (especially for past data)

**Comment by morchickit** [comment]
So past data is fine. Current Knesset is a mess. This specific vote as well, since all of the opposition members here were opposition in the last Knesset too.

**Comment by alonisser** [comment]
@morchickit  I think I found the problem:
Take a look at https://oknesset.org/admin/mks/coalitionmembership/
there are no coalition memberships for current knesset parties!(there is a Party model of each knesset) so the way the algorithm works I think that all the actual coalition mks there would be calculated as "the opposition view" for this .
Fixing this would be the first step going ahead. Then we'll have to retrigger the calculation for current Knesset.. Which shouldn't be too difficult hacking around.
So please take care of updating the missing coalition membership data and tell me when done and I'll write something to retrigger the calculation

**Comment by alonisser** [comment]
@morchickit  I also think there should be some kind of "check list" of things that should not be forgotten in new knesset..

**Comment by morchickit** [comment]
@alonisser - thanks for spotting that!
I will update it in the DB. 
and a big +1 for documentation for the the next Knesset. 
Will add it to our list.

**Comment by morchickit** [comment]
Done! I added end dates to previous coalition members and updated the new parties in the coalition. LMK if you need me to do anything else.

**Comment by alonisser** [comment]
Thanks, 
1. I run the "update_vote_properties" on this specific vote and it looks fixed now (for opposition)
I'll prepare a management command to update all the votes from current knesset . so we can fix all of them.
2. Now I can see another issue there, two coalition members are flagged as "voted against the opposition" please open a different ticket for that. I think this is a different issue

**Comment by OriHoch** [comment]
@alonisser  - please write in the v3.1.0 release notes what needs to run to update all votes
it can be python code to run in django shell on the server
https://github.com/hasadna/Open-Knesset/releases/tag/untagged-4c94ff56aac33c97c6a0

**Comment by alonisser** [comment]
@OriHoch added as requested

**Comment by alonisser** [comment]
fixed in 3.3 . would run the script today to close
