### ISSUE TITLE
Add "abstains" or "Didn't vote" fields to votes

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#514]
Currently we don't show MK who "abstaining" from voting on a proposal or attending but not voting... This data are registered in the Knesset dataset

**Comment by alonisser** [comment]
@morchickit  can you be more specific where this should be displayed?

**Comment by morchickit** [comment]
Currently display for each vote the MK that voted for and against a bill. However, there are also votes that are abstained (נמנע) which for some reason we don't show. 
See this screenshot from the Knesset website:
![screen shot 2016-02-13 at 20 08 44](https://cloud.githubusercontent.com/assets/3273659/13029783/a9ceff90-d28d-11e5-896d-2a3d6e790632.png)

**Comment by alonisser** [comment]
Looks like this data is already scraped and in the model (also I can't check without access to the production db) but my question was where and how do you want to display this..screenshot would be best (I'm just wiring the backend now, so adding the front is next thing to do)

**Comment by morchickit** [comment]
OK... so:

In the main "votes" pages - https://oknesset.org/vote/ 
I would like to ad the number of abstain in a white circle
![screen shot 2016-02-13 at 20 19 32](https://cloud.githubusercontent.com/assets/3273659/13029838/49da9f84-d28f-11e5-9ef0-683c0d85f8c3.png)

In the the specific vote page, to add a box under the for and against vote - 
![screen shot 2016-02-13 at 20 19 19](https://cloud.githubusercontent.com/assets/3273659/13029847/6db6d3fa-d28f-11e5-9abd-06cd2c9305f8.png)

**Comment by alonisser** [comment]
@morchickit Please separate two different issues. I can close the main votes pages now, but the second Issue I need to learn the code first, see if we have the data etc.. So better to separate

**Comment by alonisser** [comment]
I'll close this issue with the first change, so open another for the second

**Comment by morchickit** [comment]
Go for it. :-)

**Comment by alonisser** [comment]
Done :)

**Comment by alonisser** [comment]
Never mind.. I'll add the extra commit here
