### ISSUE TITLE
broken image

### ISSUE THREAD

**Issue by maryLoi** [hasadna/Open-Knesset#516]
https://www.oknesset.org/member/878/%D7%99%D7%90%D7%99%D7%A8-%D7%9C%D7%A4%D7%99%D7%93/

יאיר לפיד -> אג'נדות בולטות ->  שקיפות המידע הציבורי לכנסת ה-20

התנועה לחופש המידע image is broken

**Comment by morchickit** [comment]
It works on my browser...

**Comment by morchickit** [comment]
I am closing it. it works on my machine.
