### ISSUE TITLE
Hide הצעות לסדר יום section from the main committee page

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#520]
Currently this part is not updated at all, and it is based on old user suggestions.

**Comment by alonisser** [comment]
Do you mean the part: "הצעות ממתינות"? which I admit is currently quite strange

**Comment by morchickit** [comment]
הצעות ממתינות only admins can see. I mean this:
![screen shot 2016-02-13 at 16 59 56](https://cloud.githubusercontent.com/assets/3273659/13028857/5638ae7c-d273-11e5-8018-da2fa3659ca6.png)

**Comment by morchickit** [comment]
@alonisser @shevyk @RacheliRoval - When I think about it, there is no description anywhere about what הצעות לסדר יום suppose to do. I assume it is for users to mark important sessions fro them. I think we should hide it until we will understand if we want to keep it or not.

**Comment by alonisser** [comment]
@morchickit Hiding for now is trivial. Should I?

**Comment by alonisser** [comment]
@morchickit  BTW I don't think I'm an admin and yet I do see "הצעות ממתינות" I just registered to the site and saw it

**Comment by morchickit** [comment]
Please do! 
And good to know about הצעות ממתינות, i will look at it

**Comment by alonisser** [comment]
done. in PR
