### ISSUE TITLE
Add the Ethics Committee

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#526]
Currently it's not on Open Knesset... 
http://main.knesset.gov.il/Activity/Committees/Ethics/Pages/default.aspx

@OriHoch - Do I need to add manually?

**Comment by alonisser** [comment]
@morchickit I think you need to add through the admin, I can add it through a db migration if needed, but not sure what is the practice in this project

**Comment by morchickit** [comment]
I added the ethics committee to the DB. I think now we just need to link it to the appropriate protocols that we bring from the API? @OriHoch , ideas?

**Comment by OriHoch** [comment]
looks like they don't publish protocols for this committee.. that's also why it didn't appear in the first place

could you please have a look and see if you can find any protocols for this committee on knesset website?

**Comment by morchickit** [comment]
So this committee doesn't have protocols, they have a different type of doc called "החלטות ועדת האתיקה" . There is a link to all of them - http://main.knesset.gov.il/activity/committees/ethics/Pages/CommitteeDecisions.aspx
כל חברי הועדה חייבים לנכוח בה כשהיא מתכנסת..

**Comment by morchickit** [comment]
BTW - the ethics committee also updates this document, which approves MK's trips abroad. I think that making this accessible to the public is also important. http://main.knesset.gov.il/Activity/committees/Ethics/Documents/MkAbroad.pdf

**Comment by OriHoch** [comment]
this will be fixed in #534
