### ISSUE TITLE
Omit feature public opinion from bills

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#530]
I really don't think we should have this feature...
@shevyk ? 
![screen shot 2016-02-14 at 20 37 57](https://cloud.githubusercontent.com/assets/3273659/13036283/f61a831a-d35a-11e5-9cde-c115399c8d6c.png)

**Comment by shevyk** [comment]
I agree. It's not being used at all.

---
Shevy Korzen, CEO
The Public Knowledge Workshop
Tel. 972.558.837.613
shevy@hasadna.org.il | @hasadna
http://www.hasadna.org.il

**Comment by OriHoch** [comment]
deployed, looks ok
