### ISSUE TITLE
make sure the stream logger doesn't write anything to files

### ISSUE THREAD

**Issue by OriHoch** [hasadna/Open-Knesset#536]
the stream logger (introduced in #531) is great, but we just need to make sure this output is not somehow written to files (because a lot of debug info might be output there)

**Comment by OriHoch** [comment]
some places I can think of:
* cronjobs
* supervisor

**Comment by alonisser** [comment]
I'll check, Although supposedly they aren't supposed to bother each other. are we using supervisor to run? if so where is the config so I can check how logging is handled (usually supervisor is logging from stdout/stderr to a file rotating defined in it's setup, so actually it can replace the django file logger currently used ) you can cherry pick this out of the current PR and I'll build a fuller logging config in a different pr, with clearer definitions of what is being logged where

**Comment by alonisser** [comment]
Looks ok
