### ISSUE TITLE
when recreating a vote - vote id shouldn't change

### ISSUE THREAD

**Issue by OriHoch** [hasadna/Open-Knesset#546]
### Reproduction Steps
* look for a vote on the site, note it's url (e.g. https://oknesset.org/vote/8361/)
* go to admin > laws > votes
* check the checkbox next to this vote and run the action "recreate votes" on it
* now, try to go to it's old URL 

#### Expected
* vote should appear on the same URL (with the same vote id)

#### Actual
* 404 Page Not Found error (because the vote id doesn't exist anymore)

**Comment by alonisser** [comment]
@OriHoch not sure why this is important, since all other functionality would work. Only problematic (I think) if a user bookmarks this deep link for some reason.

**Comment by OriHoch** [comment]
the case of a direct link to a vote is what worries be.. for example, people might link to a vote from Facebook or other site

Not sure if it actually happens but I think it should be easy to fix so worth fixing it
