### ISSUE TITLE
we should have a process that ensures all votes data is correct

### ISSUE THREAD

**Issue by OriHoch** [hasadna/Open-Knesset#547]
currently, we have some old votes which might be wrong, for example - if an MK was not recognized and now we do recognize him, the vote might not have the correct member.

Need to go over all votes (at least of current knesset), compare their data with the new scraper data and fix / recreate the votes

This is also related to #449

**Comment by alonisser** [comment]
@OriHoch Is there an algorithm allowing us to identify wrong votes? running on all votes is quite expensive (currently)

**Comment by OriHoch** [comment]
yes, there should be a better way, I'm working on it..

**Comment by OriHoch** [comment]
this issue is on hold because we can't get votes from the knesset dataservice api at the moment (see #549)

**Comment by OriHoch** [comment]
ok, it's back.. I'm working on it :)

**Comment by OriHoch** [comment]
I'm running the validator now on all votes since 2014-11-17

**Comment by OriHoch** [comment]
looks like my validator relied on a feature which has a bug in knesset dataservice: https://github.com/hasadna/knesset-data/issues/22

waiting for that bug to be fixed..
