### ISSUE TITLE
Apologetic wording in about

### ISSUE THREAD

**Issue by alonisser** [hasadna/Open-Knesset#550]
front page:

האתר עדיין בפיתוח, ואנו מתנצלים מראש על באגים ושגיאות בנתונים.

Maybe:
האתר נמצא בפיתוח פעיל. אנא דווחו לנו על באגים ו/או שגיאות בנתונים.

**Comment by noamelf** [comment]
+1

**Comment by morchickit** [comment]
I can't find where the text in the about page. Where is it? Link?

**Comment by morchickit** [comment]
OK, it's actually on the home page, not in the about page... o_0

**Comment by morchickit** [comment]
Changed.
