### ISSUE TITLE
Agendas with no voting data show a random list of mks as "most supporting" and "most against"

### ISSUE THREAD

**Issue by alonisser** [hasadna/Open-Knesset#554]
all with zero percent vote
I guess the correct UI would be just showing empty boxes (or not showing the most supporting and most against boxes at all)
Any other ideas on that?

![zero_vote_agenda](https://cloud.githubusercontent.com/assets/1434992/13197482/6f11fe88-d7f7-11e5-9fc5-bc44afbeea29.png)

**Comment by morchickit** [comment]
:-\ It's Agendas, for now this is low priority...

**Comment by alonisser** [comment]
easily solvable..

**Comment by morchickit** [comment]
Time estimate?

**Comment by alonisser** [comment]
I guess an hour max, quite possible less

**Comment by morchickit** [comment]
Go for it, but do Speak to Alon Antin about it as well... (Why he is not on the repo is a different question...

**Comment by antin** [comment]
this is not a problem for the regular users, only for admin. you can close it.

**Comment by OriHoch** [comment]
tested on production, looks good
