### ISSUE TITLE
Attendance In committees is inaccurate 

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#562]
See the pic below for overall attendance in the Drugs and Alcohol committee - 
![screen shot 2016-02-22 at 20 14 25](https://cloud.githubusercontent.com/assets/3273659/13228428/a6acf790-d9a4-11e5-8bba-5c0fc2e8f3d8.png)

**Comment by alonisser** [comment]
I don't understand the meeting is from 2015
While it states "השנה" attendance. what does "השנה" refer to? 2015? 2016? תעש"ו?

**Comment by morchickit** [comment]
I have no clue what is the logic now. I think it needs to be per sit (מושב). @shevyk ?

**Comment by alonisser** [comment]
@morchickit the code calculates from the beginning of Gregorian year, so now is calculated from 1.1.16.  But I can change to what ever preference you have. maybe a "year ago"? moshav is quite a short period and in the first month or two would display almost always empty

**Comment by shevyk** [comment]
I think the Gregorian year doesn't make any sense in this case. I'm for
seat מושב or dropping this number altogether.

---
Shevy Korzen, CEO
The Public Knowledge Workshop
Tel. 972.558.837.613
shevy@hasadna.org.il | @hasadna
http://www.hasadna.org.il

**Comment by alonisser** [comment]
+1 for dropping, looks meaningless

**Comment by OriHoch** [comment]
Another option is to add support for [feature switching](https://en.m.wikipedia.org/wiki/Feature_toggle) - that way we could hide this and only display it for certain users or with a URL parameter

This will allow us to test\refine this feature while still being able to say that data is accurate.

**Comment by alonisser** [comment]
I can add feature toggle support, I was thinking along those lines (in work
I use them extensively, although not in django context) anyway for other
things here..

But for this specific case I'm in favor of just not displaying the number,
until we decide what is the desired outcome. when we do add, we can add
with a feature toggle to protect during qa




Twitter:@alonisser <https://twitter.com/alonisser>
LinkedIn Profile <http://www.linkedin.com/in/alonisser>
Facebook <https://www.facebook.com/alonisser>
*Tech blog:*4p-tech.co.il/blog
*Personal Blog:*degeladom.wordpress.com
Tel:972-54-6734469

**Comment by morchickit** [comment]
So... i was thinking about it a bit more. Two problems:
1. Committees have meetings sometimes even during breaks between Mosahavim. 
2. Journalist want us to tell them how much time an MK spends during a moshav.
3. People are being replaced during the year in committees. We need to show start date if it's different than other members...

**Comment by alonisser** [comment]
So looks like this needs more thinking about what's desired.. :)

**Comment by morchickit** [comment]
OK, After looking at this with the finance committee, I was thinking of the following:
1. This logic will show attendance per Moshav. Moshav will be calculated from the day it begin until the day before the new moshav start (and not the official moshav end date). This is because some committees still meet during the break between moshav.
2. Overall attendance to the whole knesset - Meaning from the day the specific knesset begins until it elections. This is to show the overall attendance and show progress (between Moshavs). 

I guess this means we need to have a Moshav feature in the DB, but this is the need that we need.

**Comment by OriHoch** [comment]
1. about moshav - I opened a new issue to handle it in a later milestone - #584
2. about the bugs in attendance - there are multiple problems there, I opened a new issue to handle those as well - #583

closing this issue
