### ISSUE TITLE
General bugs in committees

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#563]
ועדת הסמים והאלכוהול אינה מעודכנת-  
פרוטוקול אחרון באתר הכנסת הוא מ- 20.1.2016 ובאתר שלנו מ-13.10.2015
אין ישיבות קרובות
ישיבות שמהן יעלו פרוטוקול לא מעודכנות.
בפרוקוטולים קיימים חברי הכנסת אינם מופיעים כנוכחים בועדה אוטומטית וצריך להוסיף אותם ידנית.

**Comment by morchickit** [comment]
הועדה המיוחדת לסדר היום לרפורמה בשירות הציבורי -
אין ישיבות קרובות וישיבות שטרם פורסם מהם פרוטוקול

**Comment by morchickit** [comment]
ועדת הרווחה - כותרות של ועדות אינן מעודכנות 
![screen shot 2016-02-22 at 20 52 18](https://cloud.githubusercontent.com/assets/3273659/13228804/658e04c8-d9a6-11e5-8bbb-e7d7eee9a65f.png)

**Comment by morchickit** [comment]
ועדת הרווחה - ישיבה אחרונה בכנסת פתוחה היא מ- 1.2 ובאתר הכנסת ב- 10.2

**Comment by morchickit** [comment]
ועדת האתיקה - אין ישיבות קרובות. ישיבה קרובה ב-23.2 באתר הכנסת.

**Comment by morchickit** [comment]
ועדת הכנסת - ישיבה אחרונה שפורסמה ממנה פרוטוקול בכנסת פתוחה היא מ- 25.1.16 ובאתר הכנסת 17.2.16
ח"כים נוכחים אינם מופיעים בועדות מינואר. צריך להוסיף ידנית.

**Comment by RacheliRoval** [comment]
ועדת החינוך התרבות והספורט-
ישיבות קרובות כתובות בסדר כרונולוגי הפוך (מהכי רחוקה להכי קרובה). לדעתי זה מבלבל-
 ישיבות מהן טרם פורסם פרוטוקול- אותן ישיבות חוזרות על עצמן-
  חסרים פרוטוקולי הישיבות של 2.2 שכבר פורסמו באתר הכנסת-
ח"כים נוכחים בישיבות- לא מופיעים כלל-

**Comment by RacheliRoval** [comment]
ועדה מיוחדת ליישום הנגשת המידע הממשלתי:
ישיבות אחרונות- חסרים פרוטוקולים מאחת הישיבות של 15.2 והישיבות של 10.2, ו-2.2 למרות שפרוטוקולים פורסמו באתר הכנסת. חסרים פרוטוקולים של ישיבות בין 11.1 ל- 16.12  שפורסמו באתר הכנסת.
לא מופיעים כלל ח"כים נוכחים-
ישיבות מהן טרם פורסם פרוטוקול- חסרה הישיבה של ה-30.12 (נמצאת באתר הכנסת בלי פרוטוקול, לא נמצאת בכלל בכנסת פתוחה)

**Comment by RacheliRoval** [comment]
ועדה מיוחדת לדיון בהצעת חוק הרשות הממשלתית להתחדשות עירונית וכו:
אין ישיבות קרובות בכלל (למרות שיש באתר הכנסת
אין ישיבות מהן טרם פורסם פרוטוקול למרות שיש ישיבה מה-15.2 שטרם פורסם הפרוטוקול שלה
ישיבות אחרונות לא מעודכנות בכלל! הישיבה האחרונה היא מאוגוסט למרות שהתקיימו ישיבות כל שבוע בחודשים האחרונים והפרוטוקולים פורסמו באתר הכנסת. חסר גם פרוטוקול ישיבה אחת מה-20.7
נקודה לשימור: בשתי הישיבות היחידות שפורסמו (12.8 ו-28.7) הפרוטוקולים שלהם יש התאמה בין הח"כים הנוכחים למי שנכחו בפועל

**Comment by RacheliRoval** [comment]
ועדה מיוחדת לדיון בהצעת חוק השידור הציבורי:
המידע מעודכן (באמת אין ישיבות מתוכננות ואין ישיבות מהן טרם פורסם פרוטוקול. התקיימו רק שתי ישיבות של הועדה
הח"כים הנוכחים מעודכנים.
בקיצור הכל בסדר :)

**Comment by morchickit** [comment]
Ok  @OriHoch - the themes are:
1. Published Protocols are not up to date.
2. Automatic Attendance is not working. 
3. Upcoming meetings is not up-to-date
4. Sometimes, some upcoming meetings are repetitive. 
5. Meeting with no protocols are not updated.

**Comment by alonisser** [comment]
@morchickit Can you separate item 4, and add an example link, I'm not sure this is a scraping problem like the rest here

**Comment by morchickit** [comment]
See the following:
1. Published protocols - #577 
2. Automatic Attendance is not working - #578
4. Upcoming meetings is not up-to-date - #579
