### ISSUE TITLE
Some committees are not displaying protocols that are displayed on the Knesset website 

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#577]
https://oknesset.org/committee/23/ - ועדת הסמים והאלכוהול כדוגמא

**Comment by OriHoch** [comment]
@morchickit - please provide specific example

**Comment by OriHoch** [comment]
the drugs committee was duplicated on our side.. I hid the duplicated committee and merged their meetings. Looks like this was the only committee which had this problem.
