### ISSUE TITLE
Connect re:dash to Open Knesset

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#589]
So we can get data quickly and nicely and analyse it deeply :-)
 
@OriHoch - can you create a read only user on the DB and send info to Adam please?

**Comment by OriHoch** [comment]
@noamelf  - 
please add the read-only user and make sure it has permissions only for public data (e.g. not to user data etc..)

**Comment by morchickit** [comment]
I am pinging about this. @noamelf help please?

**Comment by OriHoch** [comment]
it's working! thanks @akariv 

http://data.obudget.org/ (choose dataset = open knesset)
