### ISSUE TITLE
problems with חקיקה filters

### ISSUE THREAD

**Issue by alonisser** [hasadna/Open-Knesset#594]
1. When getting into חקיקה from mk page with filter
https://oknesset.org/bill/?member=780&stage=approved
then adding more filters removes the original member filter

2. missing filter by mk

3. date pickers should display datepicker widgets

4. Missing private proposals in "סוג הצעת חוק " filter

5. Need to add an option to "reset filter"

**Comment by morchickit** [comment]
Moving to 20.1 because we need this fast.

As a user I want to see only bills that are relevant to this Knesset (or that they will be marked that way).

**Comment by OriHoch** [comment]
@alonisser @morchickit  deployed, please test
