### ISSUE TITLE
Number of bills in MK comparison does not match the actual bills that were approved

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#595]
In here - it says that Orly Levy Abekasis has 2 bills that were approved.
https://oknesset.org/member/by/bills_approved/
![screen shot 2016-03-07 at 19 00 52](https://cloud.githubusercontent.com/assets/3273659/13579788/2733c43c-e497-11e5-9192-6b71b1c619c1.png)

In Practice, the hakika page shows 3:
https://oknesset.org/bill/?member=832&stage=approved

**Comment by morchickit** [comment]
This is still not working...

**Comment by OriHoch** [comment]
@morchickit @alonisser deployed, please test

**Comment by morchickit** [comment]
Still got bugs...
see- 
https://oknesset.org/bill/?member=909&stage=approved

**Comment by morchickit** [comment]
Oh, wait, my browser fault.
