### ISSUE TITLE
חוק מתוייג כממשלתי כשהוא בכלל פרטי

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#601]
חוק הביטוח הלאומי תיקון 169 בכנסת פתוחה:
https://oknesset.org/bill/9656/

ובאתר הכנסת, בו רשום שהוא פרטי:
http://main.knesset.gov.il/Activity/Legislation/Laws/Pages/LawSecondary.aspx?lawitemid=566005

**Comment by morchickit** [comment]
other bills that are marked like that:
	חוק הסדרת העיסוק במקצועות הבריאות (תיקון מס' 4 והוראת שעה)
חוק הדיור הציבורי זכויות רכישה תיקון מס` 6 
(הצעת החוק המקורית לזכויות רכישה תיקון מס' 6 - https://oknesset.org/bill/7925/)

**Comment by alonisser** [comment]
I think those are just the same name for different laws (or perhaps a private which was merged into government) see this link from oknesset to the knesset
http://www.knesset.gov.il/Laws/Data/BillGoverment/996/996.pdf
leads to a government law as expected

**Comment by morchickit** [comment]
As discussed on Slack, they are private ones still on the Knesset website.
I will follow up with Gali to understand what's going on. but need to mark them as private.

**Comment by alonisser** [comment]
@morchickit any update on that?

**Comment by morchickit** [comment]
No, I had a crazy week, but I will catch up on this tomorrow.

**Comment by morchickit** [comment]
אוקיי, הבעיה אצלנו, עכשיו מה?

**Comment by alonisser** [comment]
@morchickit after checking with Gali?
אז אני בדקתי:

זו הצעת ממשלתית
http://knesset.gov.il/Laws/Data/BillGoverment/996/996.pdf
במערכת החוקים אמנם כתוב פרטית
http://main.knesset.gov.il/Activity/Legislation/Laws/Pages/LawSecondary.aspx?lawitemid=566005
ומפנים להצעה פרטית 1987
אבל אם נעיין בה:
http://knesset.gov.il/privatelaw/data/20/1987.rtf

אבל היא הצעה אחרת לגמרי שאמנם קשורה לביטוח לאומי ועם אותם מציעים אבל לא שייכת לנושא
בקיצור זו בעיה בכנסת לא אצלנו

סוגר אלא אם תוכיחי אחרת
