### ISSUE TITLE
Add some kind of cache busting for memcache on deploy

### ISSUE THREAD

**Issue by alonisser** [hasadna/Open-Knesset#603]

**Comment by OriHoch** [comment]
should be a fab task - which will run on deploy but also could run manually when needed

**Comment by habeanf** [comment]
We have one:
https://github.com/hasadna/Open-Knesset/blob/master/fabfile.py#L105

you can optionally request to flush it when deploying:
https://github.com/hasadna/Open-Knesset/blob/master/fabfile.py#L147

**Comment by OriHoch** [comment]
:)
