### ISSUE TITLE
In member page read more status appears even if there are no statuses at all

### ISSUE THREAD

**Issue by alonisser** [hasadna/Open-Knesset#607]

**Comment by OriHoch** [comment]
not reproduced:
https://oknesset.org/member/216/%D7%99%D7%A2%D7%A7%D7%91-%D7%9C%D7%99%D7%A6%D7%9E%D7%9F/

**Comment by alonisser** [comment]
I want to investigate this further.. Maybe the situation isn't exact, but I know I saw this..

**Comment by alonisser** [comment]
here is an example..
https://oknesset.org/member/937/%D7%90%D7%95%D7%A1%D7%90%D7%9E%D7%94-%D7%A1%D7%A2%D7%93%D7%99/

**Comment by alonisser** [comment]
Also clicking on more status just add <li>לא נמצאו סטאטוסים</li> again and again..

**Comment by OriHoch** [comment]
deployed, looks like it's fixed
