### ISSUE TITLE
Check that all the bills that passed according to מאגר חקיקה are in Open Knesset 

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#612]
As discussed last week - 
compare this:
http://main.knesset.gov.il/Activity/Legislation/Laws/Pages/LawReshumot.aspx?t=LawReshumot&st=LawReshumotBook

with our records. 

בדקו אם יש לנו חוקים ששוייכו בטעות
See this page:
https://oknesset.org/bill/?stage=6&bill_type=all&tagged=all&changed_after=&changed_before=&pp_id=&knesset_booklet=&gov_booklet=&member=

**Comment by Racvar** [comment]
https://oknesset.org/vote/9561/

יש הצבעה על אישור הצעת החוק, אבל לא הצלחנו לאתר את הצעת החוק עצמה תחת לשונית הצעות חוק.

**Comment by morchickit** [comment]
@Racvar - any more info on that?

**Comment by Racvar** [comment]
עוד סוגיות (עד כה):
תיקונים לחוק הכנסת לא מופיעים בכנסת פתוחה
חוק סליקה אלקטרונית לא מופיע תחת הצעות חוק בכנסת פתוחה
חוק להסדר התדיינות משפטיות - אין דרך ליצור קישור בין הצעת החוק להצבעה.

**Comment by morchickit** [comment]
Can you put links from the knesset site please?

**Comment by Racvar** [comment]
דבר לא ברור כל כך:
בחלק מהצעות החוק אנחנו שולפים את לשון החוק המאושר (נניח: https://oknesset.org/vote/9274/ 
 https://oknesset.org/vote/9192/ בעוד שבמקרים אחרים לשון החוק לא נשלפת - נניח ). 
לא הצלחתי למצוא את פקודת מס הכנסה תיקון 216 בכנסת פתוחה
 קצת בדומה - לשון החוק שתוקן היא לא לשון החוק https://oknesset.org/vote/9182/ 
המקום בו הדבר פורסם.

**Comment by Racvar** [comment]
עוד חוקים שלא הצלחתי למצוא באתר הכנסת:

חוק לתיקון פקודת בריאות העם וחוק צער בעלי חיים (אותו ילקוט פרסומים - 2516) 
http://fs.knesset.gov.il//20/law/20_lsr_318725.pdf

חוק חסינות חברי הכנסת - תיקון 41 http://fs.knesset.gov.il//20/law/20_lsr_318393.pdf (הצלחתי למצוא את תיקון 43, אבל לא את תיקון 41) 

הצעת חוק הטבות במס וייעוץ במס (http://fs.knesset.gov.il//20/law/20_lsr_318394.pdf) - זה מקרה חריג יחסית, כיוון שמדובר בהצעת חוק שבאישורה מתקנים שורה של חקיקות קיימות.
אישור קריאה שנייה - https://oknesset.org/vote/9095/ 
חוק ההוצאה לפועל - תיקון 48 
http://fs.knesset.gov.il//20/law/20_lsr_315851.pdf
מצאתי את אישור החוק - אבל לא את עמוד הצעת החוק כדי לקשר  
https://oknesset.org/vote/8426/

חוק העונשין תיקון 120
http://fs.knesset.gov.il//20/law/20_lsr_315852.pdf
איתרתי את ההצעה אבל לא הצלחתי למצוא את הצעת החוק אליה יש לקשר
https://oknesset.org/vote/8457/

לא בטוחה מה קרה כאן - חוברת הצעת החוק מפנה אל אותה חוברת של תיקון  12 לחוק הפיקוח על שירותים פיננסיים, אבל מדובר בשני תיקונים שונים (תיקון 13 ותיקון 12). בכל מקרה לא הצלחתי למצוא את הצעת החוק של תיקון 13 בכנסת פתוחה.
http://fs.knesset.gov.il//20/law/20_lsr_315848.pdf
https://oknesset.org/bill/9356/

חוק ההתייעלות הכלכלית ל-2009-2010 
http://fs.knesset.gov.il//20/law/20_lsr_315849.pdf

פקודת מס הכנסה תיקון 207 
אישור החוק קיים, אבל אין קישור להצעת החוק (שלא קיימת בכנסת פתוחה)
https://oknesset.org/vote/8937/
http://fs.knesset.gov.il//20/law/20_lsr_316627.pdf
(ככל הנראה זו אותה חוברת סוררת - 951) 


נשארו עוד כשלושים חוקים שאושרו תחת הכנסת הנוכחית. אשתדל להתקיל אותם השבוע (אבל סביר יותר שאגיע אליהם רק בשני הבא).

**Comment by Racvar** [comment]
את כל החקיקות הבאות לא הצלחתי לאתר בחוק הכנסת: 

 חוק עידוד תעשייה (תיקון 7) - לא הצלחתי למצוא את החוק המאושר באתר כנסת פתוחה 
http://fs.knesset.gov.il//20/law/20_lsr_313651.pdf

חוק מיסוי מקרקעין (מס שבח - תיקון 82) - לא הצלחתי למצוא את אישור החוק באתר כנסת פתוחה
http://fs.knesset.gov.il//20/law/20_lsr_314976.pdf

חוק ההוצאה לפועל תיקון 48 - לא הצלחתי למצוא את אישור החוק בכנסת פתוחה
http://fs.knesset.gov.il//20/law/20_lsr_315851.pdf

חוק העונשין - תיקון 120
http://fs.knesset.gov.il//20/law/20_lsr_315852.pdf

   - חוק פיקוח שירותים פיננסיים - תיקון 13
http://fs.knesset.gov.il//20/law/20_lsr_315848.pdf

חוק ההתייעלות הכלכלית לשנת 2009-2010
http://fs.knesset.gov.il//20/law/20_lsr_315848.pdf

**Comment by RacheliRoval** [comment]
אני רואה שיש דיליי בנתונים שלנו וש-6 הצעות שאושרו ב-7.4 עוד לא רשומות אצלנו

**Comment by morchickit** [comment]
The joy... I wonder if its an API issue

**Comment by RacheliRoval** [comment]
. באג שמצאתי בחוק השיפוט הצבאי תיקון מס` 72 עבירת עריקה
לא מצאתי אותו בחוקים שאושרו (למרות שאצלנו אושר) ואז הבנתי שזה תיקון 68 ולא 72 שאכן עבר. מה שמוזר זה שאם לוחצים על הקישור אצלנו בלשונית של ההצבעה על אישור החוק המזהה הוא נכון ורשום בכותרת שזה תיקון 68. מעניין מה גורם לבלבול...

**Comment by morchickit** [comment]
OK, we need some dev brain here. @alonisser - would you like to have a look at all of this research?

**Comment by morchickit** [comment]
@OriHoch and @alonisser - most of the issues here are around government bills. We need to check into it
