### ISSUE TITLE
Double text in events in knesset soon

### ISSUE THREAD

**Issue by alonisser** [hasadna/Open-Knesset#622]
![double_text_in_events](https://cloud.githubusercontent.com/assets/1434992/13885865/27ed2c70-ed3d-11e5-9eb3-2cf415b80eca.png)

the subject and content are sometimes the same

**Comment by alonisser** [comment]
this is linked to #623 what actually happens in that instead of committee name the text ("what") of the event is doubled as a "which", this is because of an old micro "optimization" there

**Comment by OriHoch** [comment]
deployed

**Comment by alonisser** [comment]
Checked. looks good
