### ISSUE TITLE
Write an explanation about the special committee for public broadcasting 

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#633]
בגדול, הועדה הזו דנה בחוק השידור הציבורי, העבירה אותו, והפסיקה לעבוד. צריך לכתוב הסבר עליה באתר כנסת פתוחה בכדי שהמשתמש יבין מה הוא רואה.

**Comment by Racvar** [comment]
I believe Dor already did this, I'll look it up on slack and will paste it here. 

[11:05] 
ועדה מיוחדת שהתכנסה לדון בהקמת תאגיד ציבורי שיחליף את רשות השידור הציבורית הקיימת. הדיונים עוסקים בין השאר בנושאים של מבנה התאגיד החדש, סמכויותיו, סוגי התוכן באחריותו, אופן הצגת תכנים אלו. בנוסף, עוסקים הדיונים בתהליכים נלווים והשלכות של השינוי כולל השפעות אפשרויות של קיצוץ עובדים, שינוי בתשלומי האגרה, ומציאת מתחם חלופי לתאגיד החדש.

**Comment by morchickit** [comment]
Updated!
