### ISSUE TITLE
Number of bills that passed 1st call is incorrect

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#635]
In Open Knesset Dov Hanin has 4, in Punch Banana (the Knesset system to all bills that are going through second and third readings), he has 8. 

https://oknesset.org/member/by/bills_first/

**Comment by morchickit** [comment]
@alonisser - we can also decide that we want to delete this, since the data is hard to find in the knesset data.

**Comment by alonisser** [comment]
@morchickit lets investigate first, I believe this is might be similar to #629

**Comment by alonisser** [comment]
@morchickit link to "punch banana"?

**Comment by morchickit** [comment]
http://main.knesset.gov.il/Activity/Legislation/Pages/BillForReadings2And3.aspx
