### ISSUE TITLE
votes data should be updated (currently, last vote is from March 2)

### ISSUE THREAD

**Issue by OriHoch** [hasadna/Open-Knesset#642]
see https://oknesset.org/vote/ - last vote is from March, 2 (date today is March 28)

**Comment by OriHoch** [comment]
bug was originally opened in knesset-data (https://github.com/hasadna/knesset-data/issues/32)

**Comment by shevyk** [comment]
@OriHoch votes now seem to be updated on the websןte. Can we close this issue?

**Comment by OriHoch** [comment]
yes
