### ISSUE TITLE
Bugs related to MK's atenddence in commitees

### ISSUE THREAD

**Issue by RacheliRoval** [hasadna/Open-Knesset#645]
בדיקה מדגמית של נוכחות ח״כים בישיבות ועדה מראה שלא תמיד יש התאמה מלאה בין הח״כים הנוכחים לח״כים הרשומים אצלנו. כמה בעיות שראיתי:
- די נדיר אבל אם שם של ח״כ הוא חלק משם של מוזמן אחר אז הח״כ יופיע אוטומטית. כך לדוגמא יעקב פרי מופיע בכל    הפרוטקולים של ישיבות ועדת החינוך התרבות והספורט בהן נכח סגן מנהל השירותים לבריאות הציבור במשרד הבריאות יעקב פרידברג. מצב דומה עם דוד אזולאי שהוא גם ח״כ וגם מישהו במשרד הבריאות. תיקנתי ידנית איפה שראיתי.ֿ
- באופן אקראי ח״כים לא מופיעים בישיבות בהן נכחו. ניסינו לחשוב על תבנית אבל היא לא בהכרח קיימת כך שגם אם השם בפרוטוקול רשום בדיוק כמו שהשם רשום אצלנו הוא לא תמיד מופיע (באופן בו לא יעזור להוסיף שמות חלופיים לאותו ח״כ כדי לתקן את הבעיה).
- אם שם המשפחה מופיע לפני השם הפרטי בפרוטוקול המערכת לא מזהה אותו (צריך להוסיף בשמות חלופיים)

**Comment by OriHoch** [comment]
we have another issue about better support for scraping the committee meeting attendees, in general this process should be re-written (as part of knesset-data project)

**Comment by morchickit** [comment]
@OriHoch - should I merge it with the other issue you mentioned here?

**Comment by OriHoch** [comment]
closing this issue, will add a link to it from the other issue (#583)
