### ISSUE TITLE
test_knesset_proposal_autocomplete assertions should not fail

### ISSUE THREAD

**Issue by OriHoch** [hasadna/Open-Knesset#649]
some assertions were failing, see https://travis-ci.org/hasadna/Open-Knesset/builds/121636263

I commented out the failing assertions in this commit: 948496cba2215b104535117bd3905829d0208c73

Need to fix them.. it looks like they depend on some data which does not exist.

**Comment by alonisser** [comment]
Actually I guess this means there is a bug introduced somewhere.. I'll check. The assertions are not the problem probably :)

**Comment by OriHoch** [comment]
thanks, I though it's a problem with the tests themselves because the error started on a commit which only had documentation changes, so I'm pretty sure it didn't cause it

**Comment by OriHoch** [comment]
actually, now that I think about it, the 1st test failure was on Apr. 8 - that's when we noticed knesset is blocking external traffic.. so maybe that's the cause of the bug - dependency on knesset

**Comment by alonisser** [comment]
Found it.. just a test bug, was dependent on certain dates, fixed that and pushing a fix
