### ISSUE TITLE
Facebook/twitter share metadta

### ISSUE THREAD

**Issue by alonisser** [hasadna/Open-Knesset#650]
Current sharing of oknesset content in facebook and twitter gets 'suboptimal' results - wrong picture, no description, etc. Relevant metadata should be added to index.html (currently only one facebook meta tag is implemented, and also broken)

**Comment by OriHoch** [comment]
important and quite easy to do

also, worth checking out the new facebook instant articles feature - https://developers.facebook.com/docs/instant-articles - haven't looked into it but it would be cool for example for the committee protocols to be opened in facebook that way.

**Comment by alonisser** [comment]
Do we have a facebook app id already? a twitter app id? or should I setup one?

**Comment by alonisser** [comment]
Also where can I get 200px/200px Oknesset logo?

**Comment by OriHoch** [comment]
we have some app ids in local_settings.py on production:

FACEBOOK_APP_ID = '156662232223'
SOCIAL_AUTH_TWITTER_KEY = 'mJzUBEs4ZAcZQUDcBIRg'

I don't know about the logo..

**Comment by alonisser** [comment]
@OriHoch the previous comment is real numbers? if so please remove it and I'll check in prod..

**Comment by OriHoch** [comment]
these are the public IDs  - they are exposed anyway when you use them for e.g. sharing

**Comment by alonisser** [comment]
ok ..

**Comment by alonisser** [comment]
Image still not working correctly..

**Comment by alonisser** [comment]
Also twitter not behaving as expected. argghhh

**Comment by OriHoch** [comment]
are you using the facebook debugger?

https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Foknesset.org%2F

I think the problem with the image is that you have to provide full url including domain

**Comment by alonisser** [comment]
Yap, that's the way I'm checking . I hoped using static tag would solve
this, but seems I'll have to hard code.. That's why I wanted to push to
production, so I can check this.. I'll push another fix



Twitter:@alonisser <https://twitter.com/alonisser>
LinkedIn Profile <http://www.linkedin.com/in/alonisser>
Facebook <https://www.facebook.com/alonisser>
*Tech blog:*4p-tech.co.il/blog
*Personal Blog:*degeladom.wordpress.com
Tel:972-54-6734469

**Comment by OriHoch** [comment]
@alonisser  - I added another fix for the image size (facebook requires minimum 200x200)
see e03b8dec031aa3931e645b31ddc4a2bc678be867
now it looks good

**Comment by alonisser** [comment]
Yey! I know about the minimum, but asked for help in slack to produce one, glad you could do that!
