### ISSUE TITLE
Check that the algorithm in the MK comparison for committees is right

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#654]
https://oknesset.org/member/by/committees/

Currently it looks a bit off.

**Comment by morchickit** [comment]
It looks fine now. @alonisser - did you do something to it?

**Comment by OriHoch** [comment]
@morchickit  - we made a lot of changes to the committee meetings scraping since this issue was opened, it probably fixed this problem

closing this issue
