### ISSUE TITLE
The committee for Foreign workers is still shown in the individual pages of MK's

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#655]
See Miri Regev - 
![screen shot 2016-04-10 at 17 01 14](https://cloud.githubusercontent.com/assets/3273659/14411365/e40be114-ff3d-11e5-88ae-2b31f8b9a416.png)

**Comment by alonisser** [comment]
@morchickit Why is this a bug?

**Comment by morchickit** [comment]
Because this committee does not exist anymore, and belongs to the 19th
Knesset... :-\

**Comment by alonisser** [comment]
@morchickit How is it defined in admin? how is closed defined?

**Comment by morchickit** [comment]
not in the MK page... 
and it has an end date here -https://oknesset.org/admin/committees/committee/12/

**Comment by morchickit** [comment]
I still see it on Miri Regev page...

**Comment by morchickit** [comment]
Is this because we didn't release a new version yet?

**Comment by OriHoch** [comment]
Yes, it's not deployed yet
