### ISSUE TITLE
Make an alert if the number of MK's that the system found is not equal to the ones in the committee protocol

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#659]
טוב, לפעמים המערכת עדיין לא מזהה ח״כים בפרוטוקולים.
אני מציעה שתהיה לנו התראה בדף בכל פעם אם מספר הח״כים שהאלגוריתם זיהה שונה מאלו שרשומים בפרוטוקול, זה יקל לנו על הזיהוי ויאפשר לנו להוסיף ידנית.

זה כשאני מניחה שאנחנו יכולים לספור בפרוטוקול כמה ח״כים רשומים...

**Comment by OriHoch** [comment]
we already have an issue about this in current milestone: #583 

I am closing this issue and will add a link to it in #583
