### ISSUE TITLE
bug in חוק נכי רדיפות הנאצים תיקון מס` 22

### ISSUE THREAD

**Issue by RacheliRoval** [hasadna/Open-Knesset#666]
כשנכנסים לתוכן של [הצעת החוק מ-15.2.2016](https://oknesset.org/bill/9769/), תחת הלשונית של ״יזום הצעת החוק״  מגיעים להצעת חוק הכניסה לישראל. צריך לבדוק למה מקושר להצעת החוק הלא נכונה ולתקן

**Comment by morchickit** [comment]
@OriHoch - ideas?

**Comment by morchickit** [comment]
@OriHoch  and @alonisser - can you have a look at this? It will help me for the identifiers doc for OpenKnesset

**Comment by OriHoch** [comment]
I'll have a look

**Comment by OriHoch** [comment]
It's a Knesset bug, see https://github.com/hasadna/knesset-data/issues/67

I'll fix it on our side

**Comment by OriHoch** [comment]
it's fixed on our side..
https://oknesset.org/bill/9769/
