### ISSUE TITLE
Analyse lobbyist data and get insights

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#674]
Use re:dash to find information about the lobbyist. Suggested questions: 
- Which lobbyist is the most active? 
- What committee has the most lobbyists in it?

**Comment by alonisser** [comment]
As you know lobbyist data is NOT updated currently.. There is no reason to
Analyse Non updated data

**Comment by morchickit** [comment]
I thought it was! @alonisser - what data is correct at the moment? :-(

**Comment by morchickit** [comment]
@OriHoch - see this

**Comment by alonisser** [comment]
@morchickit Ok, I might be wrong.. checking..

**Comment by shalevb** [comment]
[https://plot.ly/~shalev89/13/_1-2-3-4-5-6-7-8-9-10-11-12-13-14-15-16-17-18-19-20-21-22-24-25-26-29-30-32-33-35/?share_key=WvdfIrEI0BA3ucFrjrr4B7](url)

Lobbyists grouped by number of appearances in committee meetings

**Comment by morchickit** [comment]
Closing this since we don't have lobbyist data anymore
