### ISSUE TITLE
A data source page to the bottom toolbar

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#675]
We need to link from the bottom toolbar to this page - https://oknesset.org/datasources/

**Comment by OriHoch** [comment]
@morchickit  - we already have it, unless you meant something else

![image](https://cloud.githubusercontent.com/assets/1198854/15478104/082bef58-2121-11e6-93a6-7e15e56e0fae.png)

**Comment by morchickit** [comment]
I meant this, but I couldn't find it!
