### ISSUE TITLE
To each committee, state how many protocols are still not published 

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#677]
Since the Knesset is publishing data in delay, add a field that shows the user how many protocols are missing.

**Comment by OriHoch** [comment]
##### suggested design
show all meetings in 1 list and indicate next to each one the meeting status

we have 3 statuses - 

* upcoming meeting
* meeting without protocol
* meeting with protocol

##### actual design today
* there are 3 sections, 1 for each of the statuses

**Comment by OriHoch** [comment]
I guess my previous comment is related to #676 - I'm not sure I understand the difference between these issues

**Comment by morchickit** [comment]
כאן זה מידע סיכומי, לא לכל ועדה

**Comment by arafaeli** [comment]
Does this look alright?
![oknesset-protocol](https://cloud.githubusercontent.com/assets/10484434/15832441/eefe97b4-2c2a-11e6-85fe-0922e0e6904d.png)

**Comment by morchickit** [comment]
Looks great! Maybe -  פרוטוקולים שלא פורסמו?

**Comment by alonisser** [comment]
@morchickit perhaps something more hopeful: פרוטוקולים שטרם התפרסמו

**Comment by morchickit** [comment]
@arafaeli - אתה יכול לשנות במקום פרוטוקוים חסרים לא
פרוטוקולים שטרם פורסמו?

**Comment by arafaeli** [comment]
@morchickit - yep

**Comment by alonisser** [comment]
@arafaeli deployed can you please verify this is workin as expected?
