### ISSUE TITLE
Update all Ethics committee warnings on MK's pages 

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#678]
ועדת האתיקה של הכנסת מעניקה גינויים ואזהרות לחברי כנסת.
מה צריך לעשות?

לקרוא את החלטות ועדת האתיקה כאן - 
http://main.knesset.gov.il/activity/committees/ethics/Pages/CommitteeDecisions.aspx

לעדכן את חברי הכנסת דרך ממשק  האדמין של כנסת פתוחה.

**Comment by RacheliRoval** [comment]
מצאתי כמה באגים במהלך העבודה על עדכון נזיפות:
1. לפעמים נזיפות לא נקלטות באתר עצמו למרות שעדכנתי ושמרתי בג׳נגו - רלונטי בינתיים לסנקציות נגד חנין זועבי וג׳מאל זחאלקה מ--8.2.16 MK's- Awards
2. .  של ׳הערה של ועדת האתיקה׳ ועדכנתי עבור ח״כ אחמד טיבי וטלב אבו ערר award type הוספתי 
  בהתחלה קראתי לזה ׳הערה׳ ואז שיניתי את השם ל׳הערה של ועדת האתיקה׳ ומסיבה כלשהי התעדכן עבור טלב אבל לא עבור טיבי
@noamelf, @OriHoch can you check this please?

**Comment by RacheliRoval** [comment]
I'm done with updating all the warnings of the 20th Knesset in the Django admin, but most of them didn't actually update in open kenesset : /
 3.11.2015 אורן חזן 2.12.2015, אחמד טיבי+ זאב אלקין, 
באסל גטאס 14.7.15

**Comment by OriHoch** [comment]
we have a caching system which can make updates take longer to be seen on the site

I cleared the caches now, please check

**Comment by RacheliRoval** [comment]
It's all updated now. we can close this task.

one comment related to the knesset sight: one of the links they provide, regarding the warning of MK Moti Yogev, is wrong (they double linked another decision). so I did update the warning but didn't link the decision itself.  @morchickit / @OriHoch I wouldn't bother tell the knesset people about it but you are welcome to do it.
