### ISSUE TITLE
Fix footer

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#682]
The terms and conditions direct to the data sources of Open Knesset, but the link actually terms of use. 
https://oknesset.org/terms-of-use/

The section should direct to terms of use AND to the data sources (https://oknesset.org/datasources
![screen shot 2016-05-28 at 13 49 05](https://cloud.githubusercontent.com/assets/3273659/15627420/2b457014-24db-11e6-9f94-01e0f9f32ecd.png)

**Comment by OriHoch** [comment]
I don't understand, currently:

the text "פרטים בקישור" links to https://oknesset.org/terms-of-use/
the text "מקורות המידע של כנסת פתוחה" links to https://oknesset.org/datasources

this seems right to me

what's do you expect?

**Comment by morchickit** [comment]
Ok, it's a bit confusing. I will close this...
