### ISSUE TITLE
fix bug in Awards update system

### ISSUE THREAD

**Issue by RacheliRoval** [hasadna/Open-Knesset#683]
מצאתי כמה באגים במהלך העבודה על עדכון נזיפות של חברי כנסת:
1. :לפעמים נזיפות לא נקלטות באתר עצמו למרות שעדכנתי ושמרתי בג׳נגו - רלונטי ל MK awards
  חנין זועבי+ ג׳מאל זחאלקה 8.2.16
אורן חזן 2.12.2015
אחמד טיבי+ זאב אלקין 3.11.15
באסל גאטס 14.7.15
2. . של ׳הערה של ועדת האתיקה׳ ועדכנתי עבור ח״כ אחמד טיבי וטלב אבו ערר award type הוספתי 
בהתחלה קראתי לזה ׳הערה׳ ואז שיניתי את השם ל׳הערה של ועדת האתיקה׳ ומסיבה כלשהי התעדכן עבור טלב אבל לא עבור טיבי
@noamelf, @OriHoch can you check this please?

**Comment by OriHoch** [comment]
I did a manual cache clear, please see if it's updated now

**Comment by RacheliRoval** [comment]
It is. Great :)
