### ISSUE TITLE
Remove the English blurb from the footer 

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#684]
This blurb links to the about page, but there is no need for it. 

After removing it, we can bring the follows and terms and conditions up

**Comment by morchickit** [comment]
![screen shot 2016-05-28 at 14 36 58](https://cloud.githubusercontent.com/assets/3273659/15627622/eef9d8c8-24e1-11e6-8dce-611a7d17d279.png)

**Comment by arafaeli** [comment]
Should I remove the bottom border also?
![2016-05-30-224545_331x191_scrot](https://cloud.githubusercontent.com/assets/10484434/15657351/ba4c134c-26b8-11e6-9953-377894ad9643.png)

![2016-05-30-224606_311x209_scrot](https://cloud.githubusercontent.com/assets/10484434/15657319/6ce58dd6-26b8-11e6-8421-26453e40da6f.png)

**Comment by morchickit** [comment]
Remove away!
