### ISSUE TITLE
Sofa Landwer's page doesn't show all the committee's she's a member of

### ISSUE THREAD

**Issue by shevyk** [hasadna/Open-Knesset#687]
compare:
https://oknesset.org/member/78/%D7%A1%D7%95%D7%A4%D7%94-%D7%9C%D7%A0%D7%93%D7%91%D7%A8/
and
http://www.knesset.gov.il/mk/heb/mk.asp?mk_individual_id_t=78

the following are missing on her page on Oknesset
חברה בוועדת העבודה, הרווחה והבריאות*
 	חברה בוועדת המשנה לספורט*

Statistics of her attendance in these committees are also missing, see:
https://oknesset.org/committee/10/
https://oknesset.org/committee/6/

**Comment by OriHoch** [comment]
We have a process that updates this data but it's not run automatically

I ran it now manually and it updated the data for sofa landwer

I opened an issue to make it run automatically - #688 
about the sub-committee for sport - I opened another issue to find out why we don't have that (and other) sub-committees - #689

**Comment by shevyk** [comment]
@OriHoch Cheers!
These two committes are still not showing on her MK page
https://oknesset.org/member/78/%D7%A1%D7%95%D7%A4%D7%94-%D7%9C%D7%A0%D7%93%D7%91%D7%A8/

**Comment by OriHoch** [comment]
I cleared the cache, should be updated now

**Comment by shevyk** [comment]
Thanks!
