### ISSUE TITLE
Members from parties that do not exist in current knesset should not be part of presence scraping

### ISSUE THREAD

**Issue by alonisser** [hasadna/Open-Knesset#691]
This causes errors every night
https://opbeat.com/hasadna/openknesset-prod/errors/39/

**Comment by OriHoch** [comment]
module syncdata
filename syncdata.py
processName MainProcess
pathname /oknesset_data/oknesset/Open-Knesset/simple/management/commands/syncdata.py
lineno 1136
asctime 2016-06-13 04:20:14,151
message member שכיב שנאן (id=812) not found in presence data
funcName update_presence

**Comment by OriHoch** [comment]
we should move this to https://github.com/hasadna/knesset-data

**Comment by alonisser** [comment]
it's  a problem currently in open knesset.  Until the code migrates moving
it would just make finding the problem harder

בתאריך יום ב׳, 13 ביוני 2016, 8:56, מאת Ori Hoch ‏<notifications@github.com
