### ISSUE TITLE
Add the chairman name of a committee to the committee page

### ISSUE THREAD

**Issue by otadmor** [hasadna/Open-Knesset#701]
It is not clear whos the chairman of a committee when watching the committee page. I guess it is usually the first mk shown in the list of mks in the committee (or is it just the one who attended to most of the meetings?). as a user it is hard to understand.
Currently, finding this information requires reading of the committee logs or looking into each mk personal page.

**Comment by avirankatz** [comment]
What do you mean? Below the first MK, there is a text that says "chairman"
![capture](https://cloud.githubusercontent.com/assets/11233754/17268960/c8812866-5643-11e6-95fe-0b90727b72e0.PNG)

**Comment by otadmor** [comment]
I didnt see that.

**Comment by morchickit** [comment]
This whole page would need a make over. Until we will have one, this is closed.

**Comment by alonisser** [comment]
We can quite easily make "chairman" text in different color, or any other graphical highlighting, @morchickit perhaps consult someone with design skills (not me, no design skills)
