### ISSUE TITLE
In private bills, bills will show presenters of the bill from old Knessets, even if the bill is from current Knesset

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#714]
הצעות חוק מציגות הצעות חוק קודמות, ולכן מציגות גם את מציעי החוק הקודמים. על הצעת החוק להראות רק את מציעי החוק של ההצעה האחרונה.

ראו הצעות חוק זו כדוגמא:
https://oknesset.org/bill/5473/

Default should be:
1. If latest proposal from current knesset: show only **active** members in **current** knesset
2. else: show proposers of latest bill proposal

Optional show all proposers button to click on, would show current design
Needs design for "show all proposers"

**Comment by yotammanor** [comment]
@morchickit @alonisser 
Got back to completing this task. I finished the obligatory part.
Should I do the optional part as well?
That is, add a "Show all proposers" button, that upon clicking will display the other proposers as well?
If so - should they be pre-fetched? Or more generally, is there a place where a similar feature already exists and I can look on how it's designed and/or implemented?

**Comment by alonisser** [comment]
@yotammanor 
1. Yes should be implemented
2. Not pre fetched
3. There a couple of ajax based "more items" endpoints, I think for example in meetings for commitee

**Comment by yotammanor** [comment]
@alonisser I don't think that "more items" fits here - it is implemented assuming a "bottomless" more options (i.e. the user can always press "more items" again, and even if there's an actual limit to the number of items ,the user is unlikely to ever reach that point.)

On the other hand, in this case it should have a "show all" behaviour - once the button is clicked, there's nothing more to show. Is there a "show all" example I can follow (that is, a one that is implemented according to current coding standards)?

**Comment by alonisser** [comment]
On top of my head no.. but doesn' t look to be hard to implement, you can also just pass all data to view, and toggle only there.. performance hit is minimal in this case

**Comment by OriHoch** [comment]
@alonisser @morchickit @yotammanor  - deployed, please test (v4.6.0)
