### ISSUE TITLE
Former mk from current knesset are displayed in committee page view

### ISSUE THREAD

**Issue by alonisser** [hasadna/Open-Knesset#724]
![screenshot from 2016-10-01 02-11-15](https://cloud.githubusercontent.com/assets/1434992/19009490/3504d964-877d-11e6-90a3-0a4f364739f4.png)
For example שרון גל here

@morchickit is this by plan? or a bug

**Comment by morchickit** [comment]
A bug. A really bad one.

**Comment by alonisser** [comment]
Easy, would fix soon

**Comment by alonisser** [comment]
Turns out this is a specific bug with chairmen or replacement.. I fixed the wrong thing (commitee meeting, where non current member should appear.. ) fixing in a moment
