### ISSUE TITLE
Change first task link in Oknesset site to link to the correct label (Starter)

### ISSUE THREAD

**Issue by itaibs** [hasadna/Open-Knesset#745]
Using the link provided on the OK website to find a first task leads to an empty issues page. Makes it hard to start helping :).

Here's the link:
https://github.com/hasadna/Open-Knesset/labels/Suiteable%20as%20first%20task

**Comment by alonisser** [comment]
@itaibs Thanks for reporting

**Comment by alonisser** [comment]
@itaibs care to send a PR to fix?

**Comment by itaibs** [comment]
Sure thing :). Once I get the development environment working.

**Comment by itaibs** [comment]
@alonisser feel free to assign this to me.

**Comment by alonisser** [comment]
@itaibs You are welcome to join us on slack if you need help or discussion

**Comment by itaibs** [comment]
@alonisser Thanks! Would love to join. Anything specific I need to do? I wasn't added to any team on slack as far as I know...

**Comment by alonisser** [comment]
@itaibs I need your email to invite you ..

**Comment by itaibs** [comment]
@alonisser sure, it's itaibs@gmail.com
