### ISSUE TITLE
"Open Congress" has retired

### ISSUE THREAD

**Issue by itaibs** [hasadna/Open-Knesset#747]
In the about page, there are links to similar sites around the world. The first one leads to "Open Congress" - which is retired.

Suggestion: Change to link to "[govtrack](https://www.govtrack.us/)" which is recommended from the old open congress [website](http://www.opencongress.org/).

**Comment by alonisser** [comment]
@morchickit  what do you think?

**Comment by morchickit** [comment]
Not the same think like our "threats" -
1. GovTrack did a similar thing to Open Congress and is still alive and
kicking.
2. Sunlight retired some of their tools because they closed their lab.
Tools moved to volunteer efforts (just like GovLab).

**Comment by alonisser** [comment]
@morchickit not sure I understand the verdict.. should @itaibs change the link and the name? or maybe other suggestion?

**Comment by morchickit** [comment]
Oh! I thought you asked my opinion on it in general.

Just change to govtrack.org

**Comment by itaibs** [comment]
feel free to assign me to it. I'll get a PR soon.

**Comment by morchickit** [comment]
I can change the link. Assign it me
