### ISSUE TITLE
Bug when using django-debug-toolbar

### ISSUE THREAD

**Issue by itaibs** [hasadna/Open-Knesset#748]
When following the documentation for running the development server initially, there's a part about adding the django-debug-toolbar ([here](http://oknesset-devel.readthedocs.io/en/latest/environment/tests_db.html#enable-django-debug-toolbar)).

If you actually do that (at least on my system), you get a TypeError exception when trying to use the server. I'm pretty sure it has to do with [this bug](https://github.com/jazzband/django-debug-toolbar/issues/862) and that the toolbar needs to be upgraded.

**Comment by alonisser** [comment]
I don't I got debug toolbar to work properly and I don't like it very much (because of ajax problems), but if you manage to do so, please update the requirements file accordingly and send us a PR :)

**Comment by daonb** [comment]
or you could just remove the debug toolbar and send a PR

**Comment by alonisser** [comment]
Was removed from docs
