### ISSUE TITLE
Missing new mk מיכאל מלכיאלי

### ISSUE THREAD

**Issue by alonisser** [hasadna/Open-Knesset#755]
https://he.wikipedia.org/wiki/%D7%9E%D7%99%D7%9B%D7%90%D7%9C_%D7%9E%D7%9C%D7%9B%D7%99%D7%90%D7%9C%D7%99

@morchickit @maryLoi can one of you please add him? breaks certain things without it

**Comment by daonb** [comment]
מעתיק מצאט של @alonisser :
  באדמין שאתה בוחר הצבעה אתה יכול לבחור בפעולות:
להוריד מחדש מאתר הכנסת
זה פותר כאלו אם אתה מאתר אותם
אלא אם יש בעיה יסודית יותר כמו חבר כנסת שלא קיים אצלנו ואז זה מעיף את זה
ואז קודם צריך להוסיף אותו ואז לתקן
אתה יכול לזהות אם יש דפוס של מה חסר?

**Comment by morchickit** [comment]
בוצע. באותה הזדמנות עדכנתי את תאריך הסיום של אריה דרעי, כדי שיהיו לנו 120 ח"כים
