### ISSUE TITLE
Check votes with missing count

### ISSUE THREAD

**Issue by alonisser** [hasadna/Open-Knesset#757]
Current votes (from db)
Is there a pattern for this?
10615
10613
10612
10611
10610
10609
10608
10607
10606
10605
10604
10603
10582
10581
10580
10579
10578
10577
10576
10575
10574
10573
10602
10601
10600
10599
10598
10597
10596
10595
10594
10593
10592
10591
10590
10589
10588
10587
10586
10585
10584
10583
10614
10572
10571
10570
10569
10568
10566
10565
10564
10563
10561
10562
9323

**Comment by daonb** [comment]
yes there is. #758 should fix it.
