### ISSUE TITLE
Ads while searching for content on OKnesset 

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#766]
See this screenshot. Can we do something about it? 
![screen shot 2016-11-30 at 15 31 38](https://cloud.githubusercontent.com/assets/3273659/20758685/81fdc7e8-b712-11e6-8e24-1e0905e81113.png)

**Comment by alonisser** [comment]
Strange, can't reproduce this even with my adblock turned off.  Any way I guess hasadna has some google friends who can help perhaps? I don't know of a way to control this

**Comment by yotammanor** [comment]
Shevy mentioned it in a discussion with me once. I don't remember what she
said, but she definitely knows what's the deal.

**Comment by alonisser** [comment]
Closing for now, the way to solve this is moving to our own search. This is the deal with using google search

**Comment by OriHoch** [comment]
@morchickit - did you mean the ads are not appropriate? I think we might have some control over which ads are showing..

**Comment by OriHoch** [comment]
oh, it was from 2016..
