### ISSUE TITLE
Hide MK Attendance Pane

### ISSUE THREAD

**Issue by yotammanor** [hasadna/Open-Knesset#773]
As discussed on #562.
Hiding should be done using a Waffle flag/Switch.

Current example:
![image](https://cloud.githubusercontent.com/assets/5147457/21148493/1b87a282-c161-11e6-8271-f2eff8a23ef9.png)

The attendance data should be switched off.

requested by @shevyk in conversation.

**Comment by alonisser** [comment]
@yotammanor Until we fix it to be moshav?

**Comment by yotammanor** [comment]
@alonisser yes.
