### ISSUE TITLE
דף הצעת חוק לא קיים

### ISSUE THREAD

**Issue by maryLoi** [hasadna/Open-Knesset#786]
ייצוג הולם של בני האוכלוסייה החרדית ושל עולים חדשים בשירות הציבורי (תיקוני חקיקה), התשע"ז-2016

הצעת החוק [באתר הכנסת](http://main.knesset.gov.il/Activity/Legislation/Laws/Pages/LawBill.aspx?t=lawsuggestionssearch&lawitemid=564123)

בכ"פ קיימים [אישור החוק](https://oknesset.org/vote/10736/) ו-[דיון בוועדה](https://oknesset.org/committee/meeting/13250/)

**Comment by alonisser** [comment]
יש
https://oknesset.org/bill/9132/
אין קישור אוטומטי כי שם החוק השתנה מהפורמט המקורי
(הורידו את יהודים)
כדאי להריץ חיפוש באתר עם חלק מהמחרוזת שם בפעם הבאה כדי לדעת בדיוק
