### ISSUE TITLE
חסרים נוסח ואישור הצעת החוק עבור "חוק שירותי הדת

### ISSUE THREAD

**Issue by maryLoi** [hasadna/Open-Knesset#787]
חוק שירותי הדת היהודיים תיקון - הסדרת ייעוד השימוש במקווה טהרה
https://www.oknesset.org/bill/9812

חסר נוסח הצעת החוק של הוועדה
חסר אישור הצעת החוק

המקור בכנס
http://main.knesset.gov.il/Activity/Legislation/Laws/Pages/LawBill.aspx?t=lawsuggestionssearch&lawitemid=563604

**Comment by alonisser** [comment]
מרי חייבים שהדיווחים האלו יהיו מדוייקים
החוק שקישרת אליו הוא חוק אחר
גם הוא תיקון של חוק שירותי טהרה אבל עם יוזמים אחרים ועוסק בהובלת נפטרים ולא במקווה טהרה
נראה לי שמדובר בעצם ב
http://main.knesset.gov.il/Activity/Legislation/Laws/Pages/LawBill.aspx?t=lawsuggestionssearch&lawitemid=576492

לגבי המקור את יכולה כמובן לערוך ולהוסיף  - זה התפקיד של הטיוב
אני לא יודע למה זה לא נכנס בזמנו

לגבי האישור - מבקש שתחקרי את זה באופן כללי יותר
האם יש בעיה כללית עם אישורים חסרים? ולאיזה סוג של הצעות חוק כדי שנוכל לטפל בזה
