### ISSUE TITLE
נוסח הצעת החוק של הוועדה - לא ניתן לנתק

### ISSUE THREAD

**Issue by maryLoi** [hasadna/Open-Knesset#788]
אם נעשה קישור שגוי, לא ניתן לנתק אותו בעזרת הממשק
לדוגמה כאן
https://oknesset.org/bill/7885/

**Comment by alonisser** [comment]
תאפייני בבקשה מה הפונקציונאליות הנדרשת והאם אי אפשר לעשות אותה גם באדמין
לא נלהב להשקיע בממשק הזה כרגע כי לא יודע אם וכמה הוא ימשיך בכלל

**Comment by maryLoi** [comment]
דוגמה: הזנתי בקוביה של "נוסח הצעת החוק של הוועדה" בטעות קישור שגוי, או שהקישור הוטומטי היה שגוי. כעת אין לי דרך לנתק/להחליף אותו דרך ממשק הניהול- ממורקר בצהוב

![image](https://cloud.githubusercontent.com/assets/8996235/21453391/20c489dc-c917-11e6-8229-f5da1783f2bd.png)
