### ISSUE TITLE
כפל דפי הצבעה

### ISSUE THREAD

**Issue by maryLoi** [hasadna/Open-Knesset#790]
https://www.oknesset.org/vote/10008
https://www.oknesset.org/vote/10007

הכותרות זהות. יש דקה של הפרש זמן בין שתי ההצבעות. תוצאות ההצבעה שונות

**Comment by maryLoi** [comment]
דוגמה נוספת. כאן גם הזמנים זהים

https://www.oknesset.org/vote/9712/
https://www.oknesset.org/vote/9713/

**Comment by maryLoi** [comment]
מצב תקין שמתקיימות שתי הצבעות טרומיות צמודות על שני חוקים עם נוסחים כמעט זהים

**Comment by alonisser** [comment]
כאמור זה באג בכנסת  אם זה באג בכלל
בבקשה לבדוק קישור לכנסת לראות 
אם מספר ההצבעה בכנסת שונה אם שונה אזי לא בעיה אצלנו
