### ISSUE TITLE
אופציה לקשר ישיבות הוועדה, לוועדות אחרי קריאה ראשונה

### ISSUE THREAD

**Issue by maryLoi** [hasadna/Open-Knesset#794]
לא קיימת אופציה לקישר

**Comment by alonisser** [comment]
תאפייני בבקשה בעוד כמה מילים לפי מה יעבוד הממשק הזה

**Comment by maryLoi** [comment]
טקסט-בוקס עם אפשרות לקשר לועדה המתאימה, כמו שיש למשל בקריאה ראשונה ובשאר השלבים

![image](https://cloud.githubusercontent.com/assets/8996235/21472509/94f94af6-cae6-11e6-97d3-108629437f64.png)

כמו כן להוסיף אפשרות לנתק את הקישור אם הוא שגוי - איקס קטן כמו שיש מתחת לתאריך בקריאה טרומית
לדוגמה פה לא ניתן לנתק את הקישורים של ישיבות ועדה
![image](https://cloud.githubusercontent.com/assets/8996235/21472499/3e340774-cae6-11e6-843a-d3fddea7d19f.png)

**Comment by OriHoch** [comment]
I'm working on it..
