### ISSUE TITLE
באסל גאטס התפטר מהכנסת ובמקומו נכנס ג'מעה אזברגה

### ISSUE THREAD

**Issue by alonisser** [hasadna/Open-Knesset#827]
אצלנו זה לא מעודכן.. 
cc: @maryLoi

**Comment by OriHoch** [comment]
I'll add his basic details (because id must match knesset id)

**Comment by OriHoch** [comment]
done:
1. added ג'מעה אזברגה - only the most basic details, need to fill some more details
2. removed באסל גאטס

**Comment by OriHoch** [comment]
https://oknesset.org/member/958/%D7%92%D7%9E%D7%A2%D7%94-%D7%90%D7%96%D7%91%D7%A8%D7%92%D7%94/

**Comment by OriHoch** [comment]
https://oknesset.org/parties-members/20/
