### ISSUE TITLE
Certain mk presence was not calculated due to redundant and deprecated check in presence parsing fails on certain mks 

### ISSUE THREAD

**Issue by alonisser** [hasadna/Open-Knesset#828]
Presence parsing (mishkan) was using a redundant and deprecated check  if presence should be calculated to a period to mk. this check (mk end_date) is wrong since only "is_current" mks are being processed for presence. and "end_date" for mk is deprecated. (mks can return to knesset after "ending" a previous tenure)

**Comment by OriHoch** [comment]
after PR #830 is merged - I assume it will only be fixed for future data

do we need to run anything to re-scrape / re-calculate old data?

**Comment by alonisser** [comment]
It would update automatically for 2017, after deploy I need to do something manuall on the server to update the periods before

**Comment by OriHoch** [comment]
@alonisser what's the status? should I assign for someone else to complete this for the hackathon (which is starting today..)

**Comment by OriHoch** [comment]
related but not contradicting issue: hasadna/knesset-data-python#15

**Comment by alonisser** [comment]
@OriHoch as I said it needs to be deployed and then I can run the fix.. was it deployed? the issue was not updated with a deploy

**Comment by alonisser** [comment]
@OriHoch Also not merged. .. so why the status question? After merge and deploy 2017 would be fixed automatically and I need to do something manual (completely manual.. ) to update 2016-2015

**Comment by OriHoch** [comment]
I was waiting for you to merge and deploy it.. but I guess we had a misunderstanding.. no problem, I'll merge

**Comment by OriHoch** [comment]
deployed

**Comment by alonisser** [comment]
WIll do. later today

**Comment by alonisser** [comment]
Confirmed working, now running 2015-2016 also (And clean web python cache to see results. would happen soon)

**Comment by alonisser** [comment]
Finished and fixed. Sorry for the misunderstanding about deploy/merge

**Comment by OriHoch** [comment]
cool, thanks!
