### ISSUE TITLE
Bills based solely on a private proposals are not automatically advanced in stages when proposal is voted on

### ISSUE THREAD

**Issue by alonisser** [hasadna/Open-Knesset#829]
This isn't a very common case, which is might this has slipped under radar until now. most private proposals don't make it to an approved bill or are replaced by a knesset/government proposal in a later stage

**Comment by alonisser** [comment]
Probably the reason for #795

**Comment by OriHoch** [comment]
here too I think we will need to run something to update old votes, no?

**Comment by alonisser** [comment]
I believe old votes were fixed manually by @maryLoi when we started discussing that

**Comment by maryLoi** [comment]
זו בעיה עקבית. המון הצ"ח עם שלבים לא מעודכנים וגם עם הצבעות ודיוני ועדות חסרים. הינה הקובץ עם תיעוד מסודר. אם אפשר לתקן ולא להסתמך על טיוב ידני זה מאוד מאוד מאוד יעזור. מאוד

https://docs.google.com/spreadsheets/d/1L587-g8o-7QepSH1k2TbMLhKq04skQGUyl01E7KIe8I

**Comment by alonisser** [comment]
@maryLoi  בדקתי חלק מאלו בקובץ
כל אלו דברים שאמורים להסתדר עם  הAPI החדש
יש שם הצעות חוק עם מיזוגים ושינויי שמות למשל
יש הצעות חוק פרטיות אחרי ה20.3 שזה האחרונות שיש לנו 
ראי הודעה בסלאק שמבקשת טיפול שלך או של שבי עם הכנסת בזה
וכו'

**Comment by OriHoch** [comment]
at the moment, I think best (and possibly only) way forward is to move to the new APIs

so this issue should be on hold, until we move to the new API for getting the legislature data

**Comment by OriHoch** [comment]
blocked by the following issue: hasadna/knesset-data#127 - which handles moving the legislature data to the new API via the knesset-data projects

**Comment by alonisser** [comment]
Why block this for now? do you have a time estimate for https://github.com/hasadna/knesset-data/issues/127 ?

**Comment by OriHoch** [comment]
my mistake, it was merged

**Comment by OriHoch** [comment]
deployed
@alonisser I'm not sure what to test here, but site seems stable..
